// Code generated by dagnabit; DO NOT EDIT.

package purse

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/golf/purse"

type (
	HTTPPostAction      = internal.HTTPPostAction
	Mapping             = internal.Mapping
	MappingBuilder      = internal.MappingBuilder
	MappingEntryBuilder = internal.MappingEntryBuilder
	MappingFile         = internal.MappingFile
	Notification        = internal.Notification
	NotifyCondition     = internal.NotifyCondition
	Plugin              = internal.Plugin
	PluginBuilder       = internal.PluginBuilder
	ToolSuggestion      = internal.ToolSuggestion
)

var (
	NewMappingBuilder = internal.NewMappingBuilder
	NewPluginBuilder  = internal.NewPluginBuilder
	WriteGlobal       = internal.WriteGlobal
	WritePlugin       = internal.WritePlugin
	WriteProject      = internal.WriteProject
)

const (
	BuiltinBash  = internal.BuiltinBash
	BuiltinEdit  = internal.BuiltinEdit
	BuiltinGlob  = internal.BuiltinGlob
	BuiltinGrep  = internal.BuiltinGrep
	BuiltinRead  = internal.BuiltinRead
	BuiltinWrite = internal.BuiltinWrite
)
