// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package flag_policy

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/flag_policy"

type FlagPolicy = internal.FlagPolicy

const (
	FlagPolicyAppend = internal.FlagPolicyAppend
	FlagPolicyReset  = internal.FlagPolicyReset
)
