// Code generated by dagnabit; DO NOT EDIT.

package flag_policy

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/flag_policy"

type FlagPolicy = internal.FlagPolicy

const FlagPolicyAppend = internal.FlagPolicyAppend
const FlagPolicyReset = internal.FlagPolicyReset
