// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package compression_type

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/delta/compression_type"

type (
	CompressionType           = internal.CompressionType
	ErrUnsupportedCompression = internal.ErrUnsupportedCompression
)

const (
	CompressionTypeDefault = internal.CompressionTypeDefault
	CompressionTypeEmpty   = internal.CompressionTypeEmpty
	CompressionTypeGzip    = internal.CompressionTypeGzip
	CompressionTypeNone    = internal.CompressionTypeNone
	CompressionTypeZlib    = internal.CompressionTypeZlib
	CompressionTypeZstd    = internal.CompressionTypeZstd
)
