// Code generated by dagnabit; DO NOT EDIT.

package fd

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/delta/fd"

type (
	Std = internal.Std
)

var (
	Base                     = internal.Base
	Dir                      = internal.Dir
	DirBaseOnly              = internal.DirBaseOnly
	DoesDirectoryContainPath = internal.DoesDirectoryContainPath
	Ext                      = internal.Ext
	ExtSansDot               = internal.ExtSansDot
	FileNameSansExt          = internal.FileNameSansExt
	FileNameSansExtRelTo     = internal.FileNameSansExtRelTo
	FsRootDir                = internal.FsRootDir
	MakeStd                  = internal.MakeStd
	MakeStdFromWriter        = internal.MakeStdFromWriter
)
