// Code generated by dagnabit; DO NOT EDIT.

package quiter

import (
	interfaces "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/interfaces"
	cmp "github.com/amarbel-llc/purse-first/libs/dewey/internal/alfa/cmp"
	errors "github.com/amarbel-llc/purse-first/libs/dewey/internal/bravo/errors"
	internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/charlie/quiter"
	"iter"
)

type (
	AsyncSerializer[T any]               = internal.AsyncSerializer[T]
	AtLeastOnce[T any]                   = internal.AtLeastOnce[T]
	StringerKeyer[T interfaces.Stringer] = internal.StringerKeyer[T]
	StringerKeyerPtr[T interfaces.Stringer, TPtr interface {
		interfaces.Ptr[T]
		interfaces.Stringer
	}] = internal.StringerKeyerPtr[T, TPtr]
)

var (
	Len             = internal.Len
	ReverseSortable = internal.ReverseSortable
	StringKeyer     = internal.StringKeyer
)

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func AddOrReplaceIfGreater[ELEMENT interface {
	interfaces.Stringer
}](set interfaces.SetMutable[ELEMENT], newElement ELEMENT, cmp cmp.Func[ELEMENT]) (shouldAdd bool, err error) {
	return internal.AddOrReplaceIfGreater[ELEMENT](set, newElement, cmp)
}
func AddString[ELEMENT any, ELEMENT_PTR interfaces.SetterPtr[ELEMENT]](adder interfaces.Adder[ELEMENT], value string) (err error) {
	return internal.AddString[ELEMENT, ELEMENT_PTR](adder, value)
}
func AppendSeq[ELEMENT any, APPENDER interface {
	Append(...ELEMENT)
}](collection APPENDER, seq iter.Seq[ELEMENT]) {
	internal.AppendSeq[ELEMENT, APPENDER](collection, seq)
}
func AppendSeq2[INDEX any, ELEMENT any, APPENDER interface {
	Append(...ELEMENT)
}](collection APPENDER, seq iter.Seq2[INDEX, ELEMENT]) {
	internal.AppendSeq2[INDEX, ELEMENT, APPENDER](collection, seq)
}
func Chain[T any](e T, wfs ...interfaces.FuncIter[T]) (err error) {
	return internal.Chain[T](e, wfs...)
}
func CollectError[ELEMENT any](seq iter.Seq2[ELEMENT, error]) ([]ELEMENT, error) {
	return internal.CollectError[ELEMENT](seq)
}
func CollectSlice[ELEMENT any](collection interfaces.Collection[ELEMENT]) (slice []ELEMENT) {
	return internal.CollectSlice[ELEMENT](collection)
}
func DerivedValues[E any, F any](c interfaces.Set[E], f interfaces.FuncTransform[E, F]) (out []F, err error) {
	return internal.DerivedValues[E, F](c, f)
}
func ElementsSorted[T any](s interfaces.Collection[T], sf func(T, T) bool) (out []T) {
	return internal.ElementsSorted[T](s, sf)
}
func ErrorWaitGroupApply[T any](wg errors.WaitGroup, s interfaces.Collection[T], f interfaces.FuncIter[T]) bool {
	return internal.ErrorWaitGroupApply[T](wg, s, f)
}
func MakeAsyncSerializer[T any](wf interfaces.FuncIter[T]) internal.AsyncSerializer[T] {
	return internal.MakeAsyncSerializer[T](wf)
}
func MakeChain[T any](wfs ...interfaces.FuncIter[T]) interfaces.FuncIter[T] {
	return internal.MakeChain[T](wfs...)
}
func MakeChainDebug[T any](wfs ...interfaces.FuncIter[T]) interfaces.FuncIter[T] {
	return internal.MakeChainDebug[T](wfs...)
}
func MakeFuncAddString[ELEMENT any, ELEMENT_PTR interfaces.SetterPtr[ELEMENT]](adder interfaces.Adder[ELEMENT]) interfaces.FuncSetString {
	return internal.MakeFuncAddString[ELEMENT, ELEMENT_PTR](adder)
}
func MakeIterDebug[T any](f interfaces.FuncIter[T]) interfaces.FuncIter[T] {
	return internal.MakeIterDebug[T](f)
}
func MakeSeqErrorEmpty[ELEMENT any]() iter.Seq2[ELEMENT, error] {
	return internal.MakeSeqErrorEmpty[ELEMENT]()
}
func MakeSeqErrorFromSeq[ELEMENT any](iter iter.Seq[ELEMENT]) iter.Seq2[ELEMENT, error] {
	return internal.MakeSeqErrorFromSeq[ELEMENT](iter)
}
func MakeSeqErrorWithError[ELEMENT any](err error) iter.Seq2[ELEMENT, error] {
	return internal.MakeSeqErrorWithError[ELEMENT](err)
}
func MakeSyncSerializer[ELEMENT any](funk interfaces.FuncIter[ELEMENT]) interfaces.FuncIter[ELEMENT] {
	return internal.MakeSyncSerializer[ELEMENT](funk)
}
func MergeSeqErrorLeft[ELEMENT any, ELEMENT_PTR interfaces.Ptr[ELEMENT]](seqLeft iter.Seq2[ELEMENT_PTR, error], seqRight iter.Seq2[ELEMENT_PTR, error], funcCmp func(ELEMENT_PTR, ELEMENT_PTR) cmp.Result) iter.Seq2[ELEMENT_PTR, error] {
	return internal.MergeSeqErrorLeft[ELEMENT, ELEMENT_PTR](seqLeft, seqRight, funcCmp)
}
func MergeStreamPreferringLeft[ELEMENT any, ELEMENT_PTR interfaces.Ptr[ELEMENT]](pullLeft func() (ELEMENT_PTR, error, bool), pullRight func() (ELEMENT_PTR, error, bool), funcCmp func(ELEMENT_PTR, ELEMENT_PTR) cmp.Result) iter.Seq2[ELEMENT_PTR, error] {
	return internal.MergeStreamPreferringLeft[ELEMENT, ELEMENT_PTR](pullLeft, pullRight, funcCmp)
}
func Multiplex[T any](e interfaces.FuncIter[T], producers ...func(interfaces.FuncIter[T]) error) (err error) {
	return internal.Multiplex[T](e, producers...)
}
func PrintPointer[T any, TPtr interfaces.Ptr[T]](e TPtr) (err error) {
	return internal.PrintPointer[T, TPtr](e)
}
func Pull[ELEMENT any](seq iter.Seq[ELEMENT]) (func() (ELEMENT, bool), func()) {
	return internal.Pull[ELEMENT](seq)
}
func Pull2[ELEMENT_ONE any, ELEMENT_TWO any](seq iter.Seq2[ELEMENT_ONE, ELEMENT_TWO]) (func() (ELEMENT_ONE, ELEMENT_TWO, bool), func()) {
	return internal.Pull2[ELEMENT_ONE, ELEMENT_TWO](seq)
}
func PullError[ELEMENT any](seq iter.Seq2[ELEMENT, error]) (func() (ELEMENT, error, bool), func()) {
	return internal.PullError[ELEMENT](seq)
}
func PullErrorWithoutOk[ELEMENT any, ELEMENT_PTR interfaces.Ptr[ELEMENT]](seq iter.Seq2[ELEMENT_PTR, error]) (func() (ELEMENT_PTR, error), func()) {
	return internal.PullErrorWithoutOk[ELEMENT, ELEMENT_PTR](seq)
}
func SortedStrings[ELEMENT interfaces.Stringer](collections ...interfaces.Collection[ELEMENT]) (out []string) {
	return internal.SortedStrings[ELEMENT](collections...)
}
func SortedValues[ELEMENT interfaces.Value](seq iter.Seq[ELEMENT]) []ELEMENT {
	return internal.SortedValues[ELEMENT](seq)
}
func SortedValuesBy[ELEMENT any](set interfaces.Collection[ELEMENT], cmp cmp.Func[ELEMENT]) []ELEMENT {
	return internal.SortedValuesBy[ELEMENT](set, cmp)
}
func StringCommaSeparated[ELEMENT interfaces.Stringer](collections ...interfaces.Collection[ELEMENT]) string {
	return internal.StringCommaSeparated[ELEMENT](collections...)
}
func StringDelimiterSeparated[ELEMENT interfaces.Stringer](delimiter string, collections ...interfaces.Collection[ELEMENT]) string {
	return internal.StringDelimiterSeparated[ELEMENT](delimiter, collections...)
}
func Strings[ELEMENT interfaces.Stringer](collections iter.Seq[interfaces.Collection[ELEMENT]]) iter.Seq[string] {
	return internal.Strings[ELEMENT](collections)
}
