// Code generated by dagnabit; DO NOT EDIT.

package quiter

import (
	internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/charlie/quiter"
	cmp "github.com/amarbel-llc/purse-first/libs/dewey/pkgs/cmp"
	errors "github.com/amarbel-llc/purse-first/libs/dewey/pkgs/errors"
	interfaces "github.com/amarbel-llc/purse-first/libs/dewey/pkgs/interfaces"
)

type AsyncSerializer[T any] = internal.AsyncSerializer[T]
type AtLeastOnce[T any] = internal.AtLeastOnce[T]
type StringerKeyer[T interfaces.Stringer] = internal.StringerKeyer[T]
type StringerKeyerPtr[T interfaces.Stringer, TPtr interface {
	interfaces.Ptr[T]
	interfaces.Stringer
}] = internal.StringerKeyerPtr[T, TPtr]

var Len = internal.Len
var ReverseSortable = internal.ReverseSortable
var StringKeyer = internal.StringKeyer

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func AddOrReplaceIfGreater[ELEMENT interface {
	interfaces.Stringer
}](set interfaces.SetMutable[ELEMENT], newElement ELEMENT, cmp cmp.Func[ELEMENT]) (shouldAdd bool, err error) {
	return internal.AddOrReplaceIfGreater[ELEMENT](set, newElement, cmp)
}

// Constructs an object of type `ELEMENT` by using its `Set` method and adds it to
// the given `adder`
func AddString[ELEMENT any, ELEMENT_PTR interfaces.SetterPtr[ELEMENT]](adder interfaces.Adder[ELEMENT], value string) (err error) {
	return internal.AddString[ELEMENT, ELEMENT_PTR](adder, value)
}
func AppendSeq[ELEMENT any, APPENDER interface {
	Append(...ELEMENT)
}](collection APPENDER, seq interfaces.Seq[ELEMENT]) {
	internal.AppendSeq[ELEMENT, APPENDER](collection, seq)
}
func AppendSeq2[INDEX any, ELEMENT any, APPENDER interface {
	Append(...ELEMENT)
}](collection APPENDER, seq interfaces.Seq2[INDEX, ELEMENT]) {
	internal.AppendSeq2[INDEX, ELEMENT, APPENDER](collection, seq)
}
func Chain[T any](e T, wfs ...interfaces.FuncIter[T]) (err error) {
	return internal.Chain[T](e, wfs...)
}
func CollectError[ELEMENT any](seq interfaces.SeqError[ELEMENT]) ([]ELEMENT, error) {
	return internal.CollectError[ELEMENT](seq)
}
func CollectSlice[ELEMENT any](collection interfaces.Collection[ELEMENT]) (slice []ELEMENT) {
	return internal.CollectSlice[ELEMENT](collection)
}
func DerivedValues[E any, F any](c interfaces.Set[E], f interfaces.FuncTransform[E, F]) (out []F, err error) {
	return internal.DerivedValues[E, F](c, f)
}
func ElementsSorted[T any](s interfaces.Collection[T], sf func(T, T) bool) (out []T) {
	return internal.ElementsSorted[T](s, sf)
}
func ErrorWaitGroupApply[T any](wg errors.WaitGroup, s interfaces.Collection[T], f interfaces.FuncIter[T]) bool {
	return internal.ErrorWaitGroupApply[T](wg, s, f)
}
func MakeAsyncSerializer[T any](wf interfaces.FuncIter[T]) internal.AsyncSerializer[T] {
	return internal.MakeAsyncSerializer[T](wf)
}
func MakeChain[T any](wfs ...interfaces.FuncIter[T]) interfaces.FuncIter[T] {
	return internal.MakeChain[T](wfs...)
}
func MakeChainDebug[T any](wfs ...interfaces.FuncIter[T]) interfaces.FuncIter[T] {
	return internal.MakeChainDebug[T](wfs...)
}

// returns a function that executes `AddString` for the given `adder`
func MakeFuncAddString[ELEMENT any, ELEMENT_PTR interfaces.SetterPtr[ELEMENT]](adder interfaces.Adder[ELEMENT]) interfaces.FuncSetString {
	return internal.MakeFuncAddString[ELEMENT, ELEMENT_PTR](adder)
}
func MakeIterDebug[T any](f interfaces.FuncIter[T]) interfaces.FuncIter[T] {
	return internal.MakeIterDebug[T](f)
}
func MakeSeqErrorEmpty[ELEMENT any]() interfaces.SeqError[ELEMENT] {
	return internal.MakeSeqErrorEmpty[ELEMENT]()
}
func MakeSeqErrorFromSeq[ELEMENT any](iter interfaces.Seq[ELEMENT]) interfaces.SeqError[ELEMENT] {
	return internal.MakeSeqErrorFromSeq[ELEMENT](iter)
}
func MakeSeqErrorWithError[ELEMENT any](err error) interfaces.SeqError[ELEMENT] {
	return internal.MakeSeqErrorWithError[ELEMENT](err)
}
func MakeSyncSerializer[ELEMENT any](funk interfaces.FuncIter[ELEMENT]) interfaces.FuncIter[ELEMENT] {
	return internal.MakeSyncSerializer[ELEMENT](funk)
}

// merges the two sorted sequences into a single output sequence. when `funcCmp`
// yields cmp.Equal for two elements, the left element is yielded to the output
// sequence.
func MergeSeqErrorLeft[ELEMENT any, ELEMENT_PTR interfaces.Ptr[ELEMENT]](seqLeft interfaces.SeqError[ELEMENT_PTR], seqRight interfaces.SeqError[ELEMENT_PTR], funcCmp func(ELEMENT_PTR, ELEMENT_PTR) cmp.Result) interfaces.SeqError[ELEMENT_PTR] {
	return internal.MergeSeqErrorLeft[ELEMENT, ELEMENT_PTR](seqLeft, seqRight, funcCmp)
}
func MergeStreamPreferringLeft[ELEMENT any, ELEMENT_PTR interfaces.Ptr[ELEMENT]](pullLeft interfaces.Pull2[ELEMENT_PTR, error], pullRight interfaces.Pull2[ELEMENT_PTR, error], funcCmp func(ELEMENT_PTR, ELEMENT_PTR) cmp.Result) interfaces.SeqError[ELEMENT_PTR] {
	return internal.MergeStreamPreferringLeft[ELEMENT, ELEMENT_PTR](pullLeft, pullRight, funcCmp)
}
func Multiplex[T any](e interfaces.FuncIter[T], producers ...func(interfaces.FuncIter[T]) error) (err error) {
	return internal.Multiplex[T](e, producers...)
}
func PrintPointer[T any, TPtr interfaces.Ptr[T]](e TPtr) (err error) {
	return internal.PrintPointer[T, TPtr](e)
}
func Pull[ELEMENT any](seq interfaces.Seq[ELEMENT]) (func() (ELEMENT, bool), func()) {
	return internal.Pull[ELEMENT](seq)
}
func Pull2[ELEMENT_ONE any, ELEMENT_TWO any](seq interfaces.Seq2[ELEMENT_ONE, ELEMENT_TWO]) (func() (ELEMENT_ONE, ELEMENT_TWO, bool), func()) {
	return internal.Pull2[ELEMENT_ONE, ELEMENT_TWO](seq)
}
func PullError[ELEMENT any](seq interfaces.SeqError[ELEMENT]) (func() (ELEMENT, error, bool), func()) {
	return internal.PullError[ELEMENT](seq)
}
func PullErrorWithoutOk[ELEMENT any, ELEMENT_PTR interfaces.Ptr[ELEMENT]](seq interfaces.SeqError[ELEMENT_PTR]) (func() (ELEMENT_PTR, error), func()) {
	return internal.PullErrorWithoutOk[ELEMENT, ELEMENT_PTR](seq)
}
func SortedStrings[ELEMENT interfaces.Stringer](collections ...interfaces.Collection[ELEMENT]) (out []string) {
	return internal.SortedStrings[ELEMENT](collections...)
}

// Deprecated: use collections_slice.SortedValues
func SortedValues[ELEMENT interfaces.Value](seq interfaces.Seq[ELEMENT]) []ELEMENT {
	return internal.SortedValues[ELEMENT](seq)
}

// Deprecated: use collections_slice.SortedValuesBy
func SortedValuesBy[ELEMENT any](set interfaces.Collection[ELEMENT], cmp cmp.Func[ELEMENT]) []ELEMENT {
	return internal.SortedValuesBy[ELEMENT](set, cmp)
}
func StringCommaSeparated[ELEMENT interfaces.Stringer](collections ...interfaces.Collection[ELEMENT]) string {
	return internal.StringCommaSeparated[ELEMENT](collections...)
}
func StringDelimiterSeparated[ELEMENT interfaces.Stringer](delimiter string, collections ...interfaces.Collection[ELEMENT]) string {
	return internal.StringDelimiterSeparated[ELEMENT](delimiter, collections...)
}
func Strings[ELEMENT interfaces.Stringer](collections interfaces.Seq[interfaces.Collection[ELEMENT]]) interfaces.Seq[string] {
	return internal.Strings[ELEMENT](collections)
}
