// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package collections_coding

import (
	"io"

	internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/alfa/collections_coding"
	interfaces "github.com/amarbel-llc/purse-first/libs/dewey/pkgs/interfaces"
)

type (
	EncoderJson[T any] = internal.EncoderJson[T]
	EncoderLike[T any] = internal.EncoderLike[T]
)

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func EncoderToWriter[T any](el internal.EncoderLike[T]) interfaces.FuncIter[*T] {
	return internal.EncoderToWriter[T](el)
}

func MakeEncoderJson[T any](out io.Writer) internal.EncoderJson[T] {
	return internal.MakeEncoderJson[T](out)
}
