// Code generated by dagnabit; DO NOT EDIT.

package collections_coding

import (
	internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/alfa/collections_coding"
	interfaces "github.com/amarbel-llc/purse-first/libs/dewey/pkgs/interfaces"
	"io"
)

type EncoderJson[T any] = internal.EncoderJson[T]
type EncoderLike[T any] = internal.EncoderLike[T]

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func EncoderToWriter[T any](el internal.EncoderLike[T]) interfaces.FuncIter[*T] {
	return internal.EncoderToWriter[T](el)
}
func MakeEncoderJson[T any](out io.Writer) internal.EncoderJson[T] {
	return internal.MakeEncoderJson[T](out)
}
