// Code generated by dagnabit; DO NOT EDIT.

package heap

import (
	interfaces "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/interfaces"
	cmp "github.com/amarbel-llc/purse-first/libs/dewey/internal/alfa/cmp"
	internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/delta/heap"
)

type (
	Element                                                                  = internal.Element
	ElementPtr[ELEMENT internal.Element]                                     = internal.ElementPtr[ELEMENT]
	Heap[ELEMENT internal.Element, ELEMENT_PTR internal.ElementPtr[ELEMENT]] = internal.Heap[ELEMENT, ELEMENT_PTR]
)

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func Make[ELEMENT internal.Element, ELEMENT_PTR internal.ElementPtr[ELEMENT]](equaler interfaces.Equaler[ELEMENT_PTR], lessor interfaces.Lessor[ELEMENT_PTR], resetter interfaces.ResetterPtr[ELEMENT, ELEMENT_PTR]) *internal.Heap[ELEMENT, ELEMENT_PTR] {
	return internal.Make[ELEMENT, ELEMENT_PTR](equaler, lessor, resetter)
}
func MakeHeapFromSlice[ELEMENT internal.Element, ELEMENT_PTR internal.ElementPtr[ELEMENT]](equaler interfaces.Equaler[ELEMENT_PTR], lessor interfaces.Lessor[ELEMENT_PTR], resetter interfaces.ResetterPtr[ELEMENT, ELEMENT_PTR], slice []ELEMENT_PTR) *internal.Heap[ELEMENT, ELEMENT_PTR] {
	return internal.MakeHeapFromSlice[ELEMENT, ELEMENT_PTR](equaler, lessor, resetter, slice)
}
func MakeHeapFromSliceUnsorted[ELEMENT internal.Element, ELEMENT_PTR internal.ElementPtr[ELEMENT]](equaler interfaces.Equaler[ELEMENT_PTR], lessor interfaces.Lessor[ELEMENT_PTR], resetter interfaces.ResetterPtr[ELEMENT, ELEMENT_PTR], slice []ELEMENT_PTR) *internal.Heap[ELEMENT, ELEMENT_PTR] {
	return internal.MakeHeapFromSliceUnsorted[ELEMENT, ELEMENT_PTR](equaler, lessor, resetter, slice)
}
func MakeNew[ELEMENT internal.Element, ELEMENT_PTR internal.ElementPtr[ELEMENT]](funcCmp cmp.Func[ELEMENT_PTR], resetter interfaces.ResetterPtr[ELEMENT, ELEMENT_PTR]) *internal.Heap[ELEMENT, ELEMENT_PTR] {
	return internal.MakeNew[ELEMENT, ELEMENT_PTR](funcCmp, resetter)
}
func MakeNewHeapFromSlice[ELEMENT internal.Element, ELEMENT_PTR internal.ElementPtr[ELEMENT]](funcCmp cmp.Func[ELEMENT_PTR], resetter interfaces.ResetterPtr[ELEMENT, ELEMENT_PTR], slice []ELEMENT_PTR) *internal.Heap[ELEMENT, ELEMENT_PTR] {
	return internal.MakeNewHeapFromSlice[ELEMENT, ELEMENT_PTR](funcCmp, resetter, slice)
}
func MakeNewHeapFromSliceUnsorted[ELEMENT internal.Element, ELEMENT_PTR internal.ElementPtr[ELEMENT]](funcCmp cmp.Func[ELEMENT_PTR], resetter interfaces.ResetterPtr[ELEMENT, ELEMENT_PTR], slice []ELEMENT_PTR) *internal.Heap[ELEMENT, ELEMENT_PTR] {
	return internal.MakeNewHeapFromSliceUnsorted[ELEMENT, ELEMENT_PTR](funcCmp, resetter, slice)
}
func MergeHeapAndRestore[ELEMENT internal.Element, ELEMENT_PTR internal.ElementPtr[ELEMENT]](heap *internal.Heap[ELEMENT, ELEMENT_PTR], read func() (ELEMENT_PTR, error), write interfaces.FuncIter[ELEMENT_PTR]) (err error) {
	return internal.MergeHeapAndRestore[ELEMENT, ELEMENT_PTR](heap, read, write)
}
