// Code generated by dagnabit; DO NOT EDIT.

package format

import (
	interfaces "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/interfaces"
	internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/delta/format"
)

type (
	LineWriter = internal.LineWriter
)

var (
	MakeDelimReaderConsumeEmpty  = internal.MakeDelimReaderConsumeEmpty
	MakeFormatString             = internal.MakeFormatString
	MakeFormatStringRightAligned = internal.MakeFormatStringRightAligned
	MakeLineReaderConsumeEmpty   = internal.MakeLineReaderConsumeEmpty
	MakeLineReaderPassThruEmpty  = internal.MakeLineReaderPassThruEmpty
	MakeLineWriter               = internal.MakeLineWriter
	MakeStringer                 = internal.MakeStringer
	NewLineWriter                = internal.NewLineWriter
	ReadLines                    = internal.ReadLines
	ReadSep                      = internal.ReadSep
	Write                        = internal.Write
)

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func MakeFormatStringer[ELEMENT interfaces.Stringer](sf interfaces.FuncString[interfaces.Set[ELEMENT]]) interfaces.FuncWriterFormat[interfaces.Set[ELEMENT]] {
	return internal.MakeFormatStringer[ELEMENT](sf)
}
func MakeWriter[ELEMENT any](wff interfaces.FuncWriterFormat[ELEMENT], e ELEMENT) interfaces.FuncWriter {
	return internal.MakeWriter[ELEMENT](wff, e)
}
func MakeWriterOr[A interfaces.Stringer, B interfaces.Stringer](wffA interfaces.FuncWriterFormat[A], eA A, wffB interfaces.FuncWriterFormat[B], eB B) interfaces.FuncWriter {
	return internal.MakeWriterOr[A, B](wffA, eA, wffB, eB)
}
func MakeWriterPtr[ELEMENT any](wff interfaces.FuncWriterFormat[*ELEMENT], e *ELEMENT) interfaces.FuncWriter {
	return internal.MakeWriterPtr[ELEMENT](wff, e)
}
