// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package stack_frame

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/0/stack_frame"

type (
	ErrorAndFrame         = internal.ErrorAndFrame
	ErrorStackTracer      = internal.ErrorStackTracer
	ErrorTree             = internal.ErrorTree
	ErrorsAndFramesGetter = internal.ErrorsAndFramesGetter
	Frame                 = internal.Frame
)

var (
	Errorf                    = internal.Errorf
	MakeErrorTreeOrErr        = internal.MakeErrorTreeOrErr
	MakeFrame                 = internal.MakeFrame
	MakeFrameFromRuntimeFrame = internal.MakeFrameFromRuntimeFrame
	MakeFrames                = internal.MakeFrames
	MustFrame                 = internal.MustFrame
	Wrap                      = internal.Wrap
	WrapSkip                  = internal.WrapSkip
	Wrapf                     = internal.Wrapf
)
