// Code generated by dagnabit; DO NOT EDIT.

package stack_frame

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/stack_frame"

type ErrorAndFrame = internal.ErrorAndFrame
type ErrorStackTracer = internal.ErrorStackTracer
type ErrorTree = internal.ErrorTree
type ErrorsAndFramesGetter = internal.ErrorsAndFramesGetter
type Frame = internal.Frame

var Errorf = internal.Errorf
var MakeErrorTreeOrErr = internal.MakeErrorTreeOrErr
var MakeFrame = internal.MakeFrame
var MakeFrameFromRuntimeFrame = internal.MakeFrameFromRuntimeFrame
var MakeFrames = internal.MakeFrames
var MustFrame = internal.MustFrame
var Wrap = internal.Wrap
var WrapSkip = internal.WrapSkip
var Wrapf = internal.Wrapf
