// Code generated by dagnabit; DO NOT EDIT.

package dagnabit_rust

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/echo/dagnabit_rust"

// Mover implements dagnabit.PackageMover for cargo workspaces: git-mv
// the crate directory, then rewrite every relative path-dependency in
// the workspace that the move invalidated (references TO the moved
// crate from other members, and the moved crate's OWN path-deps whose
// relative base changed), plus the [workspace] members entry. No .rs
// file is touched — crate names do not change in a pure move.
type Mover = internal.Mover
