// Code generated by dagnabit; DO NOT EDIT.

package ui

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/charlie/ui"

// TODO make utility functions
type DevPrinter = internal.DevPrinter
type HumanReadableBytes = internal.HumanReadableBytes
type Printer = internal.Printer
type Priority = internal.Priority
type TestCase[BLOB any] = internal.TestCase[BLOB]
type TestCaseInfo = internal.TestCaseInfo

var CLIErrorTreeEncoder = internal.CLIErrorTreeEncoder
var Debug = internal.Debug
var DebugAllowCommit = internal.DebugAllowCommit

// TODO replace with a dynamic `DebugOnEnv("BATS_TEST_BODY")`
var DebugBatsTestBody = internal.DebugBatsTestBody
var Err = internal.Err
var GetHumanBytesString = internal.GetHumanBytesString
var GetHumanBytesStringOrError = internal.GetHumanBytesStringOrError
var IsVerbose = internal.IsVerbose
var Log = internal.Log
var MakePrefixPrinter = internal.MakePrefixPrinter
var MakePrinter = internal.MakePrinter
var MakePrinterFromWriter = internal.MakePrinterFromWriter
var MakePrinterOn = internal.MakePrinterOn
var MakeTestCaseInfo = internal.MakeTestCaseInfo
var Null = internal.Null
var Out = internal.Out
var SetOutput = internal.SetOutput
var SetTesting = internal.SetTesting
var SetTodoOn = internal.SetTodoOn

// TODO add compile-time determined verbosity for testing / debugging
var SetVerbose = internal.SetVerbose
var Todo = internal.Todo
var TodoP0 = internal.TodoP0
var TodoP1 = internal.TodoP1
var TodoP2 = internal.TodoP2
var TodoP3 = internal.TodoP3
var TodoP4 = internal.TodoP4
var TodoP5 = internal.TodoP5

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func MakeTestCase[BLOB any](name string, blob BLOB) internal.TestCase[BLOB] {
	return internal.MakeTestCase[BLOB](name, blob)
}

const P0 = internal.P0
const P1 = internal.P1
const P2 = internal.P2
const P3 = internal.P3
const P4 = internal.P4
const P5 = internal.P5
