// Code generated by dagnabit; DO NOT EDIT.

package ui

import (
	testui "github.com/amarbel-llc/purse-first/libs/dewey/internal/alfa/test_ui"
	internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/charlie/ui"
)

type (
	DevPrinter         = internal.DevPrinter
	HumanReadableBytes = internal.HumanReadableBytes
	Printer            = internal.Printer
	Priority           = internal.Priority
	TestCase[BLOB any] = internal.TestCase[BLOB]
	TestCaseInfo       = internal.TestCaseInfo
)

var (
	CLIErrorTreeEncoder        = internal.CLIErrorTreeEncoder
	Debug                      = internal.Debug
	DebugAllowCommit           = internal.DebugAllowCommit
	DebugBatsTestBody          = internal.DebugBatsTestBody
	Err                        = internal.Err
	GetHumanBytesString        = internal.GetHumanBytesString
	GetHumanBytesStringOrError = internal.GetHumanBytesStringOrError
	IsVerbose                  = internal.IsVerbose
	Log                        = internal.Log
	MakePrefixPrinter          = internal.MakePrefixPrinter
	MakePrinter                = internal.MakePrinter
	MakePrinterFromWriter      = internal.MakePrinterFromWriter
	MakePrinterOn              = internal.MakePrinterOn
	MakeTestCaseInfo           = internal.MakeTestCaseInfo
	Null                       = internal.Null
	Out                        = internal.Out
	SetOutput                  = internal.SetOutput
	SetTesting                 = internal.SetTesting
	SetTodoOn                  = internal.SetTodoOn
	SetVerbose                 = internal.SetVerbose
	Todo                       = internal.Todo
	TodoP0                     = internal.TodoP0
	TodoP1                     = internal.TodoP1
	TodoP2                     = internal.TodoP2
	TodoP3                     = internal.TodoP3
	TodoP4                     = internal.TodoP4
	TodoP5                     = internal.TodoP5
)

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func MakeTestCase[BLOB any](name string, blob BLOB) testui.TestCase[BLOB] {
	return internal.MakeTestCase[BLOB](name, blob)
}

const (
	P0 = internal.P0
	P1 = internal.P1
	P2 = internal.P2
	P3 = internal.P3
	P4 = internal.P4
	P5 = internal.P5
)
