// Code generated by dagnabit; DO NOT EDIT.
//go:build test

package ui

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/charlie/ui"

type T = internal.T
type TestContext = internal.TestContext

var MakeT = internal.MakeT
var RunTestContext = internal.RunTestContext
