// Code generated by dagnabit (dev+unknown); DO NOT EDIT.
//go:build test

package ui

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/charlie/ui"

type (
	T           = internal.T
	TestContext = internal.TestContext
)

var (
	MakeT          = internal.MakeT
	RunTestContext = internal.RunTestContext
)
