// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package thyme

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/delta/thyme"

type Time = internal.Time

var (
	Date          = internal.Date
	Now           = internal.Now
	Parse         = internal.Parse
	TimeWithIndex = internal.TimeWithIndex
	Tyme          = internal.Tyme
)

const (
	Epoch   = internal.Epoch
	RFC3339 = internal.RFC3339
)
