// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package analyzer_seqerror

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/alfa/analyzer_seqerror"

var Analyzer = internal.Analyzer
