// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package xdg

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/echo/xdg"

type DefaultEnvVar = internal.DefaultEnvVar

// TODO replace with env_vars.BufferedCoderDotenv
type (
	Dotenv   = internal.Dotenv
	InitArgs = internal.InitArgs
	XDG      = internal.XDG
)

var (
	CeilingEnvVarName = internal.CeilingEnvVarName
	DefaultCache      = internal.DefaultCache
	DefaultConfig     = internal.DefaultConfig
	DefaultData       = internal.DefaultData
	DefaultHome       = internal.DefaultHome
	DefaultRuntime    = internal.DefaultRuntime
	DefaultState      = internal.DefaultState
)

// IsAboveCeiling reports whether dir is strictly an ancestor of any
// ceiling entry. Both dir and each ceiling are symlink-resolved before
// comparison, matching git's documented GIT_CEILING_DIRECTORIES contract.
// Entries that fail to resolve (e.g. don't exist on disk) fall back to
// filepath.Clean so the ceiling still bounds the walk by name.
var (
	IsAboveCeiling          = internal.IsAboveCeiling
	IsAtOrAboveCeiling      = internal.IsAtOrAboveCeiling
	ParseCeilingDirectories = internal.ParseCeilingDirectories
)
