// Code generated by dagnabit; DO NOT EDIT.

package xdg

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/echo/xdg"

type (
	DefaultEnvVar = internal.DefaultEnvVar
	Dotenv        = internal.Dotenv
	InitArgs      = internal.InitArgs
	XDG           = internal.XDG
)

var (
	CeilingEnvVarName       = internal.CeilingEnvVarName
	DefaultCache            = internal.DefaultCache
	DefaultConfig           = internal.DefaultConfig
	DefaultData             = internal.DefaultData
	DefaultHome             = internal.DefaultHome
	DefaultRuntime          = internal.DefaultRuntime
	DefaultState            = internal.DefaultState
	IsAboveCeiling          = internal.IsAboveCeiling
	IsAtOrAboveCeiling      = internal.IsAtOrAboveCeiling
	ParseCeilingDirectories = internal.ParseCeilingDirectories
)
