// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package trie

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/delta/trie"

type Trie = internal.Trie

var Make = internal.Make
