// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package cargo_metadata

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/alfa/cargo_metadata"

// Reader reads cargo workspace-member dependencies by shelling out to
// `cargo metadata`. Dir is the working directory to run `cargo metadata`
// from. PackagePrefixes are directory prefixes containing crates (e.g.,
// ["internal"]). Node names are crate manifest directories relative to the
// workspace root and include the prefix (e.g., "internal/alfa/store").
//
// ComponentDepth controls how many path components identify a crate node:
//   - 3 (default): prefix/level/crate (e.g., "internal/alfa/store")
//   - 2: level/crate (e.g., "alfa/store") — for repos where NATO levels are top-level dirs
//
// When Verbose is true, sources dropped because their path has fewer than
// ComponentDepth components are logged to stderr. Independent of Verbose,
// a prefix that matched sources in `cargo metadata` output but produced
// zero edges (because every source was too short) returns an error.
type Reader = internal.Reader
