// Code generated by dagnabit; DO NOT EDIT.

package output

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/golf/output"

type (
	ArrayLimits         = internal.ArrayLimits
	Defaults            = internal.Defaults
	LimitedArray[T any] = internal.LimitedArray[T]
	LimitedText         = internal.LimitedText
	PaginationInfo      = internal.PaginationInfo
	TextLimits          = internal.TextLimits
	TruncationInfo      = internal.TruncationInfo
)

var (
	LimitStderr      = internal.LimitStderr
	LimitText        = internal.LimitText
	StandardDefaults = internal.StandardDefaults
)

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func LimitArray[T any](items []T, limits internal.ArrayLimits) internal.LimitedArray[T] {
	return internal.LimitArray[T](items, limits)
}
