// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package comments

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/charlie/comments"

var (
	Change      = internal.Change
	Comment     = internal.Comment
	Decide      = internal.Decide
	GoRefactor  = internal.GoRefactor
	Implement   = internal.Implement
	Optimize    = internal.Optimize
	Parallelize = internal.Parallelize
	Performance = internal.Performance
	Refactor    = internal.Refactor
	Remove      = internal.Remove
)
