// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package mesa

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/alfa/mesa"

// Align is a column's horizontal alignment.
type Align = internal.Align

// Cell is one column's content in a row: a sequence of styled spans, so a
// single column can carry a primary value plus a trailing dim annotation.
type Cell = internal.Cell

// ColOpt configures a [Column].
type ColOpt = internal.ColOpt

// Column declares one column of the table.
type Column = internal.Column

// LegendEntry is one status-key row rendered in the footer.
type LegendEntry = internal.LegendEntry

// RenderOpt configures a call to [Table.Render].
type RenderOpt = internal.RenderOpt

// Role is a column's width behavior.
type Role = internal.Role

// Row is a rendered line: one cell per declared column.
type Row = internal.Row

// Severity is the fixed styling vocabulary carried on the wire. A consumer
// maps its domain states onto it (active -> OK, stale -> Error, remote rows
// -> Special); the renderer owns the color for each, so producers stay
// colorless. See RFC 0003 §5.
type Severity = internal.Severity

// Span is a run of text at one severity with optional emphasis. It is the
// atom of styling: the renderer colors it by Sev and owns the palette.
type Span = internal.Span

// StatusOpt configures a [Status] cell.
type StatusOpt = internal.StatusOpt

// Table is a listing: columns, rows, an optional legend, empty-state text,
// and an optional per-severity palette override. Build it with the fluent
// methods and hand it to [Table.Render] or [EncodeStream].
type Table = internal.Table

// DecodeStream reads an NDJSON stream into a [Table], enforcing the protocol
// errors of RFC 0003 §8: the first record must carry a non-empty columns
// list, versions above 1 are rejected, roles must be pin/flex, and every
// row's cell count must equal the column count.
var DecodeStream = internal.DecodeStream

// EncodeStream writes the table as an NDJSON stream: a header record then
// one record per row (RFC 0003 §1). HTML escaping is disabled so '<', '>',
// and '&' survive verbatim in cell text.
var EncodeStream = internal.EncodeStream

// Entry constructs a [LegendEntry].
var Entry = internal.Entry

// ForcePlain renders the plain TAB-separated form regardless of the writer.
var ForcePlain = internal.ForcePlain

// ForceStyle renders the styled table regardless of whether the writer is a
// terminal.
var ForceStyle = internal.ForceStyle

// Markup compiles the producer-side markup grammar into a cell of spans:
//
//	<SEV [ATTR ...]>text</SEV>   SEV a severity name, ATTR in {b, i, u}
//
// Tags are flat (non-nesting); unmarked text compiles to a neutral span; a
// literal '<' is written "\<" and a literal '\' is written "\\". See RFC
// 0003 §9. Markup is an author-time convenience — malformed input panics,
// because producers MUST resolve it before serialization and the wire only
// ever carries compiled spans. Use [ParseMarkup] to handle errors instead.
var Markup = internal.Markup

// MinWidth sets a Flex column's minimum width before ellipsizing.
var MinWidth = internal.MinWidth

// New returns an empty v1 table.
var New = internal.New

// ParseMarkup is the non-panicking form of [Markup].
var ParseMarkup = internal.ParseMarkup

// ParseSeverity maps a wire name to a Severity. ok is false for an unknown
// name; per RFC 0003 §5 callers render an unknown severity as Neutral.
var ParseSeverity = internal.ParseSeverity

// RenderStream decodes an NDJSON stream and renders it, the out-of-process
// path used by the `dewey table` CLI.
var RenderStream = internal.RenderStream

// Shrink sets a Flex column's shrink priority (lower shrinks first).
var Shrink = internal.Shrink

// Spans is a cell built from explicit spans.
var Spans = internal.Spans

// Status builds a composite status cell from ordinary spans: a glyph colored
// by sev, an optional badge, the label, and an optional dim marker. The
// result is just spans, so the wire keeps a single cell shape.
var Status = internal.Status

// Styled is a cell of one span at the given severity.
var Styled = internal.Styled

// Text is a cell of one neutral span.
var Text = internal.Text

// Width sets the target terminal width for styled rendering. Zero (the
// default) lets the renderer size to content.
var Width = internal.Width

// WithAlign sets a column's alignment.
var WithAlign = internal.WithAlign

// WithBadge appends a badge after the glyph (e.g. a repeated presence icon).
var WithBadge = internal.WithBadge

// WithGlyph overrides the status glyph (default "●").
var WithGlyph = internal.WithGlyph

// WithMarker appends a dim marker after the label (e.g. "(current)").
var WithMarker = internal.WithMarker

// Wrap makes a Flex column wrap its content across multiple lines to fit its
// width, instead of ellipsizing the overflow. The row grows as tall as its
// tallest wrapped cell.
var Wrap = internal.Wrap

const (
	Accent  = internal.Accent
	Error   = internal.Error
	Flex    = internal.Flex
	Left    = internal.Left
	Muted   = internal.Muted
	Neutral = internal.Neutral
	OK      = internal.OK
	Pin     = internal.Pin
	Right   = internal.Right
	Special = internal.Special
	Warn    = internal.Warn
)
