// Code generated by dagnabit; DO NOT EDIT.

package files

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/delta/files"

type (
	ErrNotDirectory        = internal.ErrNotDirectory
	FileType               = internal.FileType
	TemporaryFS            = internal.TemporaryFS
	WalkDirEntry           = internal.WalkDirEntry
	WalkDirEntryIgnoreFunc = internal.WalkDirEntryIgnoreFunc
)

var (
	AssertDir                                    = internal.AssertDir
	Close                                        = internal.Close
	CloseReadOnly                                = internal.CloseReadOnly
	CombinedOutput                               = internal.CombinedOutput
	Create                                       = internal.Create
	CreateExclusiveReadOnly                      = internal.CreateExclusiveReadOnly
	CreateExclusiveWriteOnly                     = internal.CreateExclusiveWriteOnly
	DirEntries                                   = internal.DirEntries
	DirNameWriterIgnoringHidden                  = internal.DirNameWriterIgnoringHidden
	DirNames                                     = internal.DirNames
	DirNames2                                    = internal.DirNames2
	DirNamesLevel2                               = internal.DirNamesLevel2
	DirectoriesRelativeTo                        = internal.DirectoriesRelativeTo
	ErrEmptyFileList                             = internal.ErrEmptyFileList
	Exists                                       = internal.Exists
	GetFileTypeForPath                           = internal.GetFileTypeForPath
	IsErrNotDirectory                            = internal.IsErrNotDirectory
	MakeDirIfNecessary                           = internal.MakeDirIfNecessary
	MakeDirIfNecessaryForStringerWithHeadAndTail = internal.MakeDirIfNecessaryForStringerWithHeadAndTail
	MakeDirNameWriterIgnoringHidden              = internal.MakeDirNameWriterIgnoringHidden
	MakeHashBucketPath                           = internal.MakeHashBucketPath
	MakeHashBucketPathJoinFunc                   = internal.MakeHashBucketPathJoinFunc
	Open                                         = internal.Open
	OpenCreate                                   = internal.OpenCreate
	OpenCreateWriteOnlyTruncate                  = internal.OpenCreateWriteOnlyTruncate
	OpenExclusive                                = internal.OpenExclusive
	OpenExclusiveReadOnly                        = internal.OpenExclusiveReadOnly
	OpenExclusiveWriteOnly                       = internal.OpenExclusiveWriteOnly
	OpenExclusiveWriteOnlyAppend                 = internal.OpenExclusiveWriteOnlyAppend
	OpenExclusiveWriteOnlyTruncate               = internal.OpenExclusiveWriteOnlyTruncate
	OpenFile                                     = internal.OpenFile
	OpenFiles                                    = internal.OpenFiles
	OpenReadOnly                                 = internal.OpenReadOnly
	OpenReadWrite                                = internal.OpenReadWrite
	PathElements                                 = internal.PathElements
	PathFromHeadAndTail                          = internal.PathFromHeadAndTail
	ReadAllString                                = internal.ReadAllString
	ReadDir                                      = internal.ReadDir
	ReadDirNamesLevel2                           = internal.ReadDirNamesLevel2
	ReadDirNamesTo                               = internal.ReadDirNamesTo
	Readlink                                     = internal.Readlink
	Rename                                       = internal.Rename
	SetAllowUserChanges                          = internal.SetAllowUserChanges
	SetAllowUserChangesRecursive                 = internal.SetAllowUserChangesRecursive
	SetDisallowUserChanges                       = internal.SetDisallowUserChanges
	TryOrMakeDirIfNecessary                      = internal.TryOrMakeDirIfNecessary
	TryOrTimeout                                 = internal.TryOrTimeout
	WalkDir                                      = internal.WalkDir
	WalkDirIgnoreFuncHidden                      = internal.WalkDirIgnoreFuncHidden
)

const (
	FileTypeData       = internal.FileTypeData
	FileTypeExecutable = internal.FileTypeExecutable
	FileTypeText       = internal.FileTypeText
	FileTypeUnknown    = internal.FileTypeUnknown
)
