// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package reset

import (
	internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/reset"
	constraints "golang.org/x/exp/constraints"
)

type (
	FuncReset[ELEMENT any]     = internal.FuncReset[ELEMENT]
	FuncResetWith[ELEMENT any] = internal.FuncResetWith[ELEMENT]
)

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func Map[KEY constraints.Ordered, VALUE any](mapp map[KEY]VALUE) (out map[KEY]VALUE) {
	return internal.Map[KEY, VALUE](mapp)
}

func Slice[ELEMENT any](in []ELEMENT) (out []ELEMENT) {
	return internal.Slice[ELEMENT](in)
}
