// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package cargo_manifest

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/0/cargo_manifest"

// AddMember appends rel to the [workspace] members array if absent
// (idempotent: a second add returns the input unchanged with
// added=false). Only multiline arrays are supported; a single-line
// `members = ["a"]` array errors with "unsupported single-line members
// array". The inserted entry matches the indentation of existing
// entries (two spaces when the array is empty).
var AddMember = internal.AddMember

// RenameDepKey renames dependency key oldName to newName: inline-table
// keys (`oldName = { … }` / `oldName = "1"`) in bare dependency
// sections, and table headers ([dependencies.oldName] and dev-/build-
// variants). Keys are matched exactly (start of line, then optional
// spaces, then `=`), never by substring.
var RenameDepKey = internal.RenameDepKey

// ReplaceMember swaps a [workspace] members entry string: the first
// quoted occurrence of oldRel on each [workspace]-section line becomes
// newRel. Returns ok=false (input unchanged) when oldRel is absent.
var ReplaceMember = internal.ReplaceMember

// RewritePathDeps replaces dependency `path = "<oldPath>"` values with
// newPath, in both inline-table deps under [dependencies] (and
// [dev-dependencies], [build-dependencies]) and table-form
// [dependencies.<name>] sections. Returns the rewritten manifest and
// the number of replacements. Zero replacements returns the input
// byte-identical.
var RewritePathDeps = internal.RewritePathDeps

// SetPackageName rewrites `name = "…"` inside the [package] section
// only, preserving spacing and trailing comments. Errors if [package]
// has no name key.
var SetPackageName = internal.SetPackageName
