// Code generated by dagnabit; DO NOT EDIT.

package script_config

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/delta/script_config"

type RemoteScript = internal.RemoteScript
type RemoteScriptWithEnv = internal.RemoteScriptWithEnv
type ScriptConfig = internal.ScriptConfig
type ScriptConfigDocument = internal.ScriptConfigDocument
type WithOutputFormat = internal.WithOutputFormat
type WithOutputFormatDocument = internal.WithOutputFormatDocument

var DecodeScriptConfig = internal.DecodeScriptConfig
var DecodeScriptConfigInto = internal.DecodeScriptConfigInto
var DecodeWithOutputFormat = internal.DecodeWithOutputFormat
var DecodeWithOutputFormatInto = internal.DecodeWithOutputFormatInto
var EncodeScriptConfigFrom = internal.EncodeScriptConfigFrom
var EncodeWithOutputFormatFrom = internal.EncodeWithOutputFormatFrom
var MakeWriterTo = internal.MakeWriterTo
var MakeWriterToWithStdin = internal.MakeWriterToWithStdin
