// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package script_config

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/delta/script_config"

type (
	RemoteScript             = internal.RemoteScript
	RemoteScriptWithEnv      = internal.RemoteScriptWithEnv
	ScriptConfig             = internal.ScriptConfig
	ScriptConfigDocument     = internal.ScriptConfigDocument
	WithOutputFormat         = internal.WithOutputFormat
	WithOutputFormatDocument = internal.WithOutputFormatDocument
)

var (
	DecodeScriptConfig         = internal.DecodeScriptConfig
	DecodeScriptConfigInto     = internal.DecodeScriptConfigInto
	DecodeWithOutputFormat     = internal.DecodeWithOutputFormat
	DecodeWithOutputFormatInto = internal.DecodeWithOutputFormatInto
	EncodeScriptConfigFrom     = internal.EncodeScriptConfigFrom
	EncodeWithOutputFormatFrom = internal.EncodeWithOutputFormatFrom
	MakeWriterTo               = internal.MakeWriterTo
	MakeWriterToWithStdin      = internal.MakeWriterToWithStdin
)
