// Code generated by dagnabit; DO NOT EDIT.

package server

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/bravo/server"

type (
	CompletionProvider  = internal.CompletionProvider
	ElicitationProvider = internal.ElicitationProvider
	Handler             = internal.Handler
	LoggingHandler      = internal.LoggingHandler
	Options             = internal.Options
	PromptProvider      = internal.PromptProvider
	PromptProviderV1    = internal.PromptProviderV1
	PromptRegistry      = internal.PromptRegistry
	PromptRenderer      = internal.PromptRenderer
	ResourceProvider    = internal.ResourceProvider
	ResourceProviderV1  = internal.ResourceProviderV1
	ResourceReader      = internal.ResourceReader
	ResourceRegistry    = internal.ResourceRegistry
	Server              = internal.Server
	TaskProvider        = internal.TaskProvider
	ToolHandler         = internal.ToolHandler
	ToolHandlerV1       = internal.ToolHandlerV1
	ToolProvider        = internal.ToolProvider
	ToolProviderV1      = internal.ToolProviderV1
	ToolRegistry        = internal.ToolRegistry
	ToolRegistryV1      = internal.ToolRegistryV1
)

var (
	New                 = internal.New
	NewHandler          = internal.NewHandler
	NewPromptRegistry   = internal.NewPromptRegistry
	NewResourceRegistry = internal.NewResourceRegistry
	NewToolRegistry     = internal.NewToolRegistry
	NewToolRegistryV1   = internal.NewToolRegistryV1
)
