// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package string_builder_joined

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/charlie/string_builder_joined"

var Make = internal.Make
