// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package analyzer_actx

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/alfa/analyzer_actx"

var Analyzer = internal.Analyzer
