// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package alfred

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/echo/alfred"

type (
	Item         = internal.Item
	ItemIcon     = internal.ItemIcon
	ItemPool     = internal.ItemPool
	ItemText     = internal.ItemText
	MatchBuilder = internal.MatchBuilder
	Mod          = internal.Mod
	Writer       = internal.Writer
)

var (
	GetPoolMatchBuilder = internal.GetPoolMatchBuilder
	MakeItemPool        = internal.MakeItemPool
	NewDebouncingWriter = internal.NewDebouncingWriter
	NewMatchBuilder     = internal.NewMatchBuilder
	NewWriter           = internal.NewWriter
)
