// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package quiter_collection

import (
	internal "code.linenisgreat.com/purse-first/libs/dewey/internal/alfa/quiter_collection"
	interfaces "code.linenisgreat.com/purse-first/libs/dewey/pkgs/interfaces"
)

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func Equals[ELEMENT interfaces.Stringer](left interfaces.Collection[ELEMENT], right interfaces.Collection[ELEMENT]) bool {
	return internal.Equals[ELEMENT](left, right)
}
