// Code generated by dagnabit; DO NOT EDIT.

package quiter_collection

import (
	interfaces "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/interfaces"
	internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/alfa/quiter_collection"
)

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func Equals[ELEMENT interfaces.Stringer](left interfaces.Collection[ELEMENT], right interfaces.Collection[ELEMENT]) bool {
	return internal.Equals[ELEMENT](left, right)
}
