// Code generated by dagnabit; DO NOT EDIT.

package unicorn

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/alfa/unicorn"

var (
	AllRunes                = internal.AllRunes
	AllRunesWithIndex       = internal.AllRunesWithIndex
	CountCase               = internal.CountCase
	CountRune               = internal.CountRune
	CutNCharacters          = internal.CutNCharacters
	ExtractUniqueComponents = internal.ExtractUniqueComponents
	IsSpace                 = internal.IsSpace
	Not                     = internal.Not
	StripDiacritics         = internal.StripDiacritics
	ToLower                 = internal.ToLower
	ToUpper                 = internal.ToUpper
)
