// Code generated by dagnabit; DO NOT EDIT.

package unicorn

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/alfa/unicorn"

var AllRunes = internal.AllRunes
var AllRunesWithIndex = internal.AllRunesWithIndex
var CountCase = internal.CountCase
var CountRune = internal.CountRune
var CutNCharacters = internal.CutNCharacters
var ExtractUniqueComponents = internal.ExtractUniqueComponents
var IsSpace = internal.IsSpace
var Not = internal.Not
var StripDiacritics = internal.StripDiacritics
var ToLower = internal.ToLower
var ToUpper = internal.ToUpper
