// Code generated by dagnabit; DO NOT EDIT.

package interfaces

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/interfaces"

type (
	ActiveContext                                               = internal.ActiveContext
	ActiveContextGetter                                         = internal.ActiveContextGetter
	Adder[ELEMENT any]                                          = internal.Adder[ELEMENT]
	CLIFlagDefinitions                                          = internal.CLIFlagDefinitions
	CLIFlagIOWrapper                                            = internal.CLIFlagIOWrapper
	Coder[OBJECT any, READER any, WRITER any]                   = internal.Coder[OBJECT, READER, WRITER]
	CoderBufferedReadWriter[OBJECT any]                         = internal.CoderBufferedReadWriter[OBJECT]
	CoderReadWriter[OBJECT any]                                 = internal.CoderReadWriter[OBJECT]
	Collection[ELEMENT any]                                     = internal.Collection[ELEMENT]
	CollectionMutable[ELEMENT any]                              = internal.CollectionMutable[ELEMENT]
	CommandComponentWriter                                      = internal.CommandComponentWriter
	Comparable[SELF any]                                        = internal.Comparable[SELF]
	CompoundKeyer[T any]                                        = internal.CompoundKeyer[T]
	ContainsKeyer                                               = internal.ContainsKeyer
	ContextState                                                = internal.ContextState
	DecoderFrom[OBJECT any, READER any]                         = internal.DecoderFrom[OBJECT, READER]
	DecoderFromBufferedReader[OBJECT any]                       = internal.DecoderFromBufferedReader[OBJECT]
	DecoderFromReader[OBJECT any]                               = internal.DecoderFromReader[OBJECT]
	Delta[ELEMENT any]                                          = internal.Delta[ELEMENT]
	DirectoryLayoutBaseEnvVar                                   = internal.DirectoryLayoutBaseEnvVar
	DirectoryLayoutPath                                         = internal.DirectoryLayoutPath
	DirectoryLayoutXDG                                          = internal.DirectoryLayoutXDG
	EncoderTo[OBJECT any, READER any]                           = internal.EncoderTo[OBJECT, READER]
	EncoderToBufferedWriter[OBJECT any]                         = internal.EncoderToBufferedWriter[OBJECT]
	EncoderToWriter[OBJECT any]                                 = internal.EncoderToWriter[OBJECT]
	EnvVars                                                     = internal.EnvVars
	EnvVarsAdder                                                = internal.EnvVarsAdder
	Equaler[ELEMENT any]                                        = internal.Equaler[ELEMENT]
	Equatable[ELEMENT any]                                      = internal.Equatable[ELEMENT]
	ErrorHiddenWrapper                                          = internal.ErrorHiddenWrapper
	ErrorManyUnwrapper                                          = internal.ErrorManyUnwrapper
	ErrorOneUnwrapper                                           = internal.ErrorOneUnwrapper
	ErrorRetryable                                              = internal.ErrorRetryable
	FlagValue                                                   = internal.FlagValue
	FuncActiveContext                                           = internal.FuncActiveContext
	FuncIter[ELEMENT any]                                       = internal.FuncIter[ELEMENT]
	FuncIterIO[ELEMENT any]                                     = internal.FuncIterIO[ELEMENT]
	FuncIterKey                                                 = internal.FuncIterKey
	FuncIterWithKey[ELEMENT any]                                = internal.FuncIterWithKey[ELEMENT]
	FuncMakePrinter[OUT any]                                    = internal.FuncMakePrinter[OUT]
	FuncRepool                                                  = internal.FuncRepool
	FuncRetry                                                   = internal.FuncRetry
	FuncRetryAborted                                            = internal.FuncRetryAborted
	FuncSetString                                               = internal.FuncSetString
	FuncString[T any]                                           = internal.FuncString[T]
	FuncStringWriterFormat[T any]                               = internal.FuncStringWriterFormat[T]
	FuncTransform[ELEMENT any, T1 any]                          = internal.FuncTransform[ELEMENT, T1]
	FuncWriter                                                  = internal.FuncWriter
	FuncWriterElementInterface[ELEMENT any]                     = internal.FuncWriterElementInterface[ELEMENT]
	FuncWriterFormat[T any]                                     = internal.FuncWriterFormat[T]
	IOWrapper                                                   = internal.IOWrapper
	Iterable[ELEMENT any]                                       = internal.Iterable[ELEMENT]
	Keyer[ELEMENT any]                                          = internal.Keyer[ELEMENT]
	Lenner                                                      = internal.Lenner
	Lessor[ELEMENT any]                                         = internal.Lessor[ELEMENT]
	LockSmith                                                   = internal.LockSmith
	LockSmithGetter                                             = internal.LockSmithGetter
	Pool[T any]                                                 = internal.Pool[T]
	PoolPtr[T any, TPtr internal.Ptr[T]]                        = internal.PoolPtr[T, TPtr]
	Printer                                                     = internal.Printer
	Ptr[T any]                                                  = internal.Ptr[T]
	Pull[ELEMENT any]                                           = internal.Pull[ELEMENT]
	Pull2[ELEMENT any, ELEMENT_TWO any]                         = internal.Pull2[ELEMENT, ELEMENT_TWO]
	ReadWrapper                                                 = internal.ReadWrapper
	Resetable                                                   = internal.Resetable
	ResetablePtr[ELEMENT any]                                   = internal.ResetablePtr[ELEMENT]
	ResetableWithError                                          = internal.ResetableWithError
	Resetter[ELEMENT any]                                       = internal.Resetter[ELEMENT]
	ResetterPtr[ELEMENT any, ELEMENT_PTR internal.Ptr[ELEMENT]] = internal.ResetterPtr[ELEMENT, ELEMENT_PTR]
	RuneDecoder                                                 = internal.RuneDecoder
	Seq[ELEMENT any]                                            = internal.Seq[ELEMENT]
	Seq2[ELEMENT any, ELEMENT_TWO any]                          = internal.Seq2[ELEMENT, ELEMENT_TWO]
	SeqError[ELEMENT any]                                       = internal.SeqError[ELEMENT]
	Set[ELEMENT any]                                            = internal.Set[ELEMENT]
	SetGetter[ELEMENT any]                                      = internal.SetGetter[ELEMENT]
	SetMutable[ELEMENT any]                                     = internal.SetMutable[ELEMENT]
	Setter                                                      = internal.Setter
	SetterPtr[T any]                                            = internal.SetterPtr[T]
	StringCoder[T any]                                          = internal.StringCoder[T]
	StringEncoderTo[T any]                                      = internal.StringEncoderTo[T]
	StringKeyer[T any]                                          = internal.StringKeyer[T]
	StringKeyerPtr[T any, TPtr internal.Ptr[T]]                 = internal.StringKeyerPtr[T, TPtr]
	StringSetterPtr[T any]                                      = internal.StringSetterPtr[T]
	Stringer                                                    = internal.Stringer
	StringerPtr[T any]                                          = internal.StringerPtr[T]
	StringerSetter                                              = internal.StringerSetter
	StringerSetterPtr[T any]                                    = internal.StringerSetterPtr[T]
	StringerWithHeadAndTail                                     = internal.StringerWithHeadAndTail
	Tridex                                                      = internal.Tridex
	TridexMutable                                               = internal.TridexMutable
	Value                                                       = internal.Value
	ValuePtr[SELF internal.Value]                               = internal.ValuePtr[SELF]
	WriteWrapper                                                = internal.WriteWrapper
	WriterAndStringWriter                                       = internal.WriterAndStringWriter
)

const (
	ContextStateAborted   = internal.ContextStateAborted
	ContextStateFailed    = internal.ContextStateFailed
	ContextStateStarted   = internal.ContextStateStarted
	ContextStateSucceeded = internal.ContextStateSucceeded
	ContextStateUnknown   = internal.ContextStateUnknown
	ContextStateUnstarted = internal.ContextStateUnstarted
)
