// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package buildinfo

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/buildinfo"

var Commit = internal.Commit

// Print writes the eng-versioning(7) version-subcommand output. Dewey
// binaries pin no downstream components, so per the spec they emit only
// the self-identification line — no blank line, no component table:
//
//	name VERSION+COMMIT
var (
	Print   = internal.Print
	Version = internal.Version
)
