// Code generated by dagnabit; DO NOT EDIT.

package buildinfo

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/buildinfo"

var Commit = internal.Commit

// Print writes the eng-versioning(7) version-subcommand output:
// a self-identification line, a blank line, then the component table
// header. Dewey binaries pin no downstreams, so the table is empty.
var Print = internal.Print
var Version = internal.Version
