// Code generated by dagnabit; DO NOT EDIT.

package equals

import (
	interfaces "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/interfaces"
	internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/alfa/equals"
)

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func Iterable[T any](a interfaces.Iterable[T], b interfaces.Iterable[T]) bool {
	return internal.Iterable[T](a, b)
}
func SetIfNotNil[TYPE any](ptr *TYPE, value TYPE) *TYPE {
	return internal.SetIfNotNil[TYPE](ptr, value)
}
func SetIfValueNotNil[TYPE any](ptr *TYPE, value *TYPE) *TYPE {
	return internal.SetIfValueNotNil[TYPE](ptr, value)
}
