package dagnabit

import (
	"os"
	"path/filepath"
	"testing"

	"code.linenisgreat.com/purse-first/libs/dewey/internal/alfa/test_ui"
)

// TestExportCopyComposesWithLibrary verifies that --copy + library mode
// walks internal/ and copies every package's source files into pkgs/.
// The same dispatch path (exportSinglePackage) is used by both
// ExportPackage and ExportAll, so this should "just work" — the test
// pins the contract.
func TestExportCopyComposesWithLibrary(t *testing.T) {
	tt := test_ui.T{T: t}
	tmpDir := t.TempDir()

	if err := os.WriteFile(filepath.Join(tmpDir, "go.mod"),
		[]byte("module example.com/mod\n\ngo 1.23\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	for _, leaf := range []string{"first", "second"} {
		dir := filepath.Join(tmpDir, "internal", "alfa", leaf)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(
			filepath.Join(dir, leaf+".go"),
			[]byte("package "+leaf+"\n\nfunc Hello() string { return \""+leaf+"\" }\n"),
			0o644,
		); err != nil {
			t.Fatal(err)
		}
	}

	exporter := &Exporter{
		ModulePath:          "example.com/mod",
		Dir:                 tmpDir,
		OutputDir:           "pkgs",
		SkipConsumerRewrite: true,
		Env:                 append(os.Environ(), "GOWORK=off"),
		Copy:                true,
	}

	if err := exporter.ExportAll(); err != nil {
		t.Fatal(err)
	}

	for _, leaf := range []string{"first", "second"} {
		out, err := os.ReadFile(filepath.Join(tmpDir, "pkgs", leaf, leaf+".go"))
		if err != nil {
			t.Fatalf("pkgs/%s/%s.go not generated: %v", leaf, leaf, err)
		}
		got := string(out)
		assertContains(tt, got, "Code generated by dagnabit (")
		assertContains(tt, got, "func Hello() string {")
		assertContains(tt, got, "return \""+leaf+"\"")
		// No internal-import alias surface in copy mode.
		assertNotContains(tt, got, "internal.Hello")
	}
}

// TestExportCopyComposesWithDirectiveScan verifies that --copy +
// `//go:generate dagnabit export` directive (ScanAndExport entry) also
// copies the source files. Confirms the dispatch point is correctly
// inside exportSinglePackage and not duplicated in ExportPackage.
func TestExportCopyComposesWithDirectiveScan(t *testing.T) {
	tt := test_ui.T{T: t}
	tmpDir := t.TempDir()

	if err := os.WriteFile(filepath.Join(tmpDir, "go.mod"),
		[]byte("module example.com/mod\n\ngo 1.23\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	pkgDir := filepath.Join(tmpDir, "internal", "alfa", "widget")
	if err := os.MkdirAll(pkgDir, 0o755); err != nil {
		t.Fatal(err)
	}
	// Construct the directive at runtime so this source file does not itself
	// contain a literal `//go:generate dagnabit export` line — which would
	// otherwise be picked up by scanForExportDirectives walking internal/.
	content := "package widget\n\n" + exportDirective + "\n\nfunc Greet() string { return \"hi\" }\n"
	if err := os.WriteFile(filepath.Join(pkgDir, "widget.go"), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}

	exporter := &Exporter{
		ModulePath:          "example.com/mod",
		Dir:                 tmpDir,
		OutputDir:           "pkgs",
		SkipConsumerRewrite: true,
		Env:                 append(os.Environ(), "GOWORK=off"),
		Copy:                true,
	}

	if err := exporter.ScanAndExport(); err != nil {
		t.Fatal(err)
	}

	out, err := os.ReadFile(filepath.Join(tmpDir, "pkgs", "widget", "widget.go"))
	if err != nil {
		t.Fatalf("pkgs/widget/widget.go not generated: %v", err)
	}
	got := string(out)
	assertContains(tt, got, "Code generated by dagnabit (")
	assertContains(tt, got, `return "hi"`)
	assertNotContains(tt, got, "internal.Greet")
}
