package dagnabit

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"golang.org/x/tools/go/packages"
)

// exportPackageAsCopy implements --copy mode: copy every non-test .go
// source file from the internal package's directory into the pkgs/
// facade directory, rewriting only intra-module imports (other
// internal/ paths → pkgs/ facade paths). The package name, build-tag
// constraints, doc comments, and unexported helpers are preserved
// verbatim because we copy the source rather than synthesize a
// re-export surface.
//
// The flag composes with --library and //go:generate dagnabit export
// because the choice between this path and the alias path lives
// inside [Exporter.exportSinglePackage], which all three entry points
// flow through.
func (exporter *Exporter) exportPackageAsCopy(pkg *packages.Package, outputSubdir string) error {
	if len(pkg.GoFiles) == 0 {
		return fmt.Errorf("package %s has no Go source files", pkg.PkgPath)
	}

	srcDir := filepath.Dir(pkg.GoFiles[0])
	entries, err := os.ReadDir(srcDir)
	if err != nil {
		return fmt.Errorf("reading source dir %s: %w", srcDir, err)
	}

	if err := os.MkdirAll(outputSubdir, 0o755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if !strings.HasSuffix(name, ".go") {
			continue
		}
		if strings.HasSuffix(name, "_test.go") {
			continue
		}

		srcPath := filepath.Join(srcDir, name)
		dstPath := filepath.Join(outputSubdir, name)

		rewritten, err := exporter.copyAndRewriteFile(srcPath)
		if err != nil {
			return fmt.Errorf("rewriting %s: %w", srcPath, err)
		}
		if err := os.WriteFile(dstPath, rewritten, 0o644); err != nil {
			return fmt.Errorf("writing %s: %w", dstPath, err)
		}
		fmt.Printf("copied: %s\n", dstPath)
	}

	return nil
}

// copyAndRewriteFile parses srcPath, rewrites any in-module
// `internal/<level>/<leaf>` import to the matching
// `<outputDir>/<leaf>` path, prepends the standard
// `Code generated by dagnabit; DO NOT EDIT.` header (preserving any
// leading `//go:build` constraint), and returns the rendered bytes.
func (exporter *Exporter) copyAndRewriteFile(srcPath string) ([]byte, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, srcPath, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parsing: %w", err)
	}

	internalPrefix := exporter.ModulePath + "/internal/"
	for _, imp := range file.Imports {
		// imp.Path.Value is the quoted import string, e.g. `"foo/bar"`.
		path, err := strconv.Unquote(imp.Path.Value)
		if err != nil {
			continue
		}
		if !strings.HasPrefix(path, internalPrefix) {
			continue
		}
		newPath := internalToFacade(exporter.ModulePath, exporter.outputDir(), path)
		imp.Path.Value = strconv.Quote(newPath)
	}

	// Sort imports so the rewritten file matches goimports' canonical
	// ordering (otherwise the rewritten paths can appear out of order
	// inside a parenthesized import block).
	ast.SortImports(fset, file)

	var body bytes.Buffer
	if err := printer.Fprint(&body, fset, file); err != nil {
		return nil, fmt.Errorf("rendering: %w", err)
	}

	// gofmt the result so tab-alignment quirks from go/printer
	// (e.g. `func f() int\t{ return 42 }`) collapse into canonical
	// gofmt spacing. The rewritten file should be byte-identical to
	// what `gofmt` would produce on the original source.
	formatted, err := format.Source(body.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt: %w", err)
	}

	return prependGeneratedHeader(formatted), nil
}

// prependGeneratedHeader prefixes the standard
// `Code generated by dagnabit; DO NOT EDIT.` comment to the rendered
// source, taking care to land it ABOVE any leading `//go:build`
// constraint with a blank line in between so the Go build system
// still recognises the constraint.
func prependGeneratedHeader(src []byte) []byte {
	header := []byte("// Code generated by dagnabit; DO NOT EDIT.\n\n")

	lines := bytes.SplitN(src, []byte("\n"), 2)
	if len(lines) >= 1 && bytes.HasPrefix(lines[0], []byte("//go:build")) {
		// Original starts with a build constraint. Keep it as the
		// FIRST line of the file (Go's build-tag parsing wants it
		// in the leading comment block before the package clause).
		// Place the Code generated header AFTER, separated by a blank
		// line so it still reads as part of the file's leading
		// comments.
		var out bytes.Buffer
		out.Write(lines[0])
		out.WriteByte('\n')
		out.WriteByte('\n')
		out.Write(header)
		if len(lines) == 2 {
			// Skip any leading blank lines from the original after
			// the build tag — we already added our own.
			rest := bytes.TrimLeft(lines[1], "\n")
			out.Write(rest)
		}
		return out.Bytes()
	}

	var out bytes.Buffer
	out.Write(header)
	out.Write(src)
	return out.Bytes()
}

