package dagnabit

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"golang.org/x/tools/go/packages"
)

// TestExportCopySourceFiles verifies the --copy mode: instead of
// generating a thin re-export facade with `var = internal.X` aliases,
// the exporter copies the actual source files from internal/<...>/<leaf>
// into pkgs/<leaf>, rewriting only intra-workspace imports
// (internal/ → pkgs/).
//
// Function bodies, type definitions, vars, consts, and unexported
// helpers are duplicated verbatim. The pkgs/ tree is a real package,
// not an alias surface.
func TestExportCopySourceFiles(t *testing.T) {
	tmpDir := t.TempDir()

	if err := os.WriteFile(filepath.Join(tmpDir, "go.mod"),
		[]byte("module example.com/mod\n\ngo 1.23\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	pkgDir := filepath.Join(tmpDir, "internal", "alfa", "widget")
	if err := os.MkdirAll(pkgDir, 0o755); err != nil {
		t.Fatal(err)
	}
	// A reasonable source file: imports, exported type, exported func,
	// unexported helper, doc comments.
	if err := os.WriteFile(filepath.Join(pkgDir, "widget.go"), []byte(`package widget

import (
	"fmt"
	"strings"
)

// Widget holds a name.
type Widget struct{ Name string }

// Greet returns "hi <name>".
func Greet(name string) string {
	return fmt.Sprintf("hi %s", strings.TrimSpace(name))
}

func unexportedHelper() int { return 42 }
`), 0o644); err != nil {
		t.Fatal(err)
	}

	exporter := &Exporter{
		ModulePath:          "example.com/mod",
		Dir:                 tmpDir,
		OutputDir:           "pkgs",
		SkipConsumerRewrite: true,
		Env:                 append(os.Environ(), "GOWORK=off"),
		Copy:                true,
	}

	if err := exporter.ExportPackage("./internal/alfa/widget"); err != nil {
		t.Fatal(err)
	}

	out, err := os.ReadFile(filepath.Join(tmpDir, "pkgs", "widget", "widget.go"))
	if err != nil {
		t.Fatalf("pkgs/widget/widget.go not generated: %v", err)
	}
	got := string(out)

	// Code-generated header is present.
	assertContains(t, got, "Code generated by dagnabit; DO NOT EDIT.")

	// External imports are preserved.
	assertContains(t, got, `"fmt"`)
	assertContains(t, got, `"strings"`)

	// Source declarations are copied verbatim, including function body
	// and unexported helper.
	assertContains(t, got, "// Widget holds a name.")
	assertContains(t, got, "type Widget struct{ Name string }")
	assertContains(t, got, "// Greet returns")
	assertContains(t, got, `return fmt.Sprintf("hi %s", strings.TrimSpace(name))`)
	assertContains(t, got, "func unexportedHelper() int { return 42 }")

	// NO alias-style re-export in copy mode.
	assertNotContains(t, got, "internal.Widget")
	assertNotContains(t, got, "internal.Greet")
	assertNotContains(t, got, `import internal "example.com/mod/internal/alfa/widget"`)
}

// TestExportCopyRewritesInternalImports verifies that when a copied
// source file imports another internal/ package, the import path is
// rewritten to point at the corresponding pkgs/ facade. External
// imports are untouched.
func TestExportCopyRewritesInternalImports(t *testing.T) {
	tmpDir := t.TempDir()

	if err := os.WriteFile(filepath.Join(tmpDir, "go.mod"),
		[]byte("module example.com/mod\n\ngo 1.23\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	depDir := filepath.Join(tmpDir, "internal", "0", "shared")
	if err := os.MkdirAll(depDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(depDir, "shared.go"), []byte(`package shared

type Token struct{ V string }
`), 0o644); err != nil {
		t.Fatal(err)
	}

	pkgDir := filepath.Join(tmpDir, "internal", "alfa", "widget")
	if err := os.MkdirAll(pkgDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(pkgDir, "widget.go"), []byte(`package widget

import (
	"fmt"

	"example.com/mod/internal/0/shared"
)

func Stringify(t shared.Token) string { return fmt.Sprintf("%q", t.V) }
`), 0o644); err != nil {
		t.Fatal(err)
	}

	exporter := &Exporter{
		ModulePath:          "example.com/mod",
		Dir:                 tmpDir,
		OutputDir:           "pkgs",
		SkipConsumerRewrite: true,
		Env:                 append(os.Environ(), "GOWORK=off"),
		Copy:                true,
	}

	if err := exporter.ExportPackage("./internal/alfa/widget"); err != nil {
		t.Fatal(err)
	}

	out, err := os.ReadFile(filepath.Join(tmpDir, "pkgs", "widget", "widget.go"))
	if err != nil {
		t.Fatalf("pkgs/widget/widget.go not generated: %v", err)
	}
	got := string(out)

	// External import untouched.
	assertContains(t, got, `"fmt"`)

	// Internal import rewritten to pkgs/ facade path.
	assertContains(t, got, `"example.com/mod/pkgs/shared"`)
	assertNotContains(t, got, `"example.com/mod/internal/0/shared"`)
}

// TestExportCopyPreservesBuildTags verifies that //go:build constrained
// files are copied with their constraints intact.
func TestExportCopyPreservesBuildTags(t *testing.T) {
	tmpDir := t.TempDir()

	if err := os.WriteFile(filepath.Join(tmpDir, "go.mod"),
		[]byte("module example.com/mod\n\ngo 1.23\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	pkgDir := filepath.Join(tmpDir, "internal", "alfa", "widget")
	if err := os.MkdirAll(pkgDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(pkgDir, "widget.go"), []byte(`package widget

type Widget struct{}
`), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(pkgDir, "debug.go"), []byte(`//go:build debug

package widget

type DebugWidget struct{}
`), 0o644); err != nil {
		t.Fatal(err)
	}

	exporter := &Exporter{
		ModulePath:          "example.com/mod",
		Dir:                 tmpDir,
		OutputDir:           "pkgs",
		SkipConsumerRewrite: true,
		Env:                 append(os.Environ(), "GOWORK=off"),
		Copy:                true,
	}

	if err := exporter.ExportPackage("./internal/alfa/widget"); err != nil {
		t.Fatal(err)
	}

	mainOut, err := os.ReadFile(filepath.Join(tmpDir, "pkgs", "widget", "widget.go"))
	if err != nil {
		t.Fatalf("pkgs/widget/widget.go not generated: %v", err)
	}
	debugOut, err := os.ReadFile(filepath.Join(tmpDir, "pkgs", "widget", "debug.go"))
	if err != nil {
		t.Fatalf("pkgs/widget/debug.go not generated: %v", err)
	}

	if strings.Contains(string(mainOut), "//go:build") {
		t.Errorf("main file should not have //go:build constraint, got:\n%s", mainOut)
	}
	if !strings.Contains(string(debugOut), "//go:build debug") {
		t.Errorf("debug file should preserve //go:build debug, got:\n%s", debugOut)
	}
	assertContains(t, string(debugOut), "type DebugWidget struct{}")
}

// TestExportCopySkipsTestFiles verifies that _test.go files are NOT
// copied. Tests belong to the internal implementation; the pkgs/ side
// is the public surface only.
func TestExportCopySkipsTestFiles(t *testing.T) {
	tmpDir := t.TempDir()

	if err := os.WriteFile(filepath.Join(tmpDir, "go.mod"),
		[]byte("module example.com/mod\n\ngo 1.23\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	pkgDir := filepath.Join(tmpDir, "internal", "alfa", "widget")
	if err := os.MkdirAll(pkgDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(pkgDir, "widget.go"), []byte(`package widget

type Widget struct{}
`), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(pkgDir, "widget_test.go"), []byte(`package widget

import "testing"

func TestNop(t *testing.T) {}
`), 0o644); err != nil {
		t.Fatal(err)
	}

	exporter := &Exporter{
		ModulePath:          "example.com/mod",
		Dir:                 tmpDir,
		OutputDir:           "pkgs",
		SkipConsumerRewrite: true,
		Env:                 append(os.Environ(), "GOWORK=off"),
		Copy:                true,
	}

	if err := exporter.ExportPackage("./internal/alfa/widget"); err != nil {
		t.Fatal(err)
	}

	if _, err := os.Stat(filepath.Join(tmpDir, "pkgs", "widget", "widget_test.go")); !os.IsNotExist(err) {
		t.Errorf("widget_test.go should not have been copied, err=%v", err)
	}
}

// TestExportCopyDanglingInternalImport pins the behavior when a
// --copy-exported package imports another internal/ package that has
// NOT itself been exported. The import is still rewritten to the
// pkgs/<leaf> facade path (because keeping the `internal/` path would
// violate Go's internal-package visibility rule for any out-of-module
// consumer), so the resulting pkgs/<leaf> file references a facade
// directory that does not exist on disk.
//
// This is the SAME caveat that alias mode has: callers exporting a
// single package via dagnabit are responsible for also exporting any
// internal/ dependencies (or for using --library, which exports every
// package under internal/). The exporter does not auto-cascade.
//
// Pinning this behavior in a test keeps the contract explicit so a
// future change (e.g. auto-warning, auto-cascade, or a hard error)
// is a deliberate decision rather than an accidental drift.
func TestExportCopyDanglingInternalImport(t *testing.T) {
	tmpDir := t.TempDir()

	if err := os.WriteFile(filepath.Join(tmpDir, "go.mod"),
		[]byte("module example.com/mod\n\ngo 1.23\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	// internal/0/shared exists but is intentionally NOT exported.
	depDir := filepath.Join(tmpDir, "internal", "0", "shared")
	if err := os.MkdirAll(depDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(depDir, "shared.go"), []byte(`package shared

type Token struct{ V string }
`), 0o644); err != nil {
		t.Fatal(err)
	}

	pkgDir := filepath.Join(tmpDir, "internal", "alfa", "widget")
	if err := os.MkdirAll(pkgDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(pkgDir, "widget.go"), []byte(`package widget

import "example.com/mod/internal/0/shared"

func Stringify(t shared.Token) string { return t.V }
`), 0o644); err != nil {
		t.Fatal(err)
	}

	exporter := &Exporter{
		ModulePath:          "example.com/mod",
		Dir:                 tmpDir,
		OutputDir:           "pkgs",
		SkipConsumerRewrite: true,
		Env:                 append(os.Environ(), "GOWORK=off"),
		Copy:                true,
	}

	// Export ONLY widget. shared is left dangling.
	if err := exporter.ExportPackage("./internal/alfa/widget"); err != nil {
		t.Fatal(err)
	}

	out, err := os.ReadFile(filepath.Join(tmpDir, "pkgs", "widget", "widget.go"))
	if err != nil {
		t.Fatalf("pkgs/widget/widget.go not generated: %v", err)
	}
	got := string(out)

	// Internal import is still rewritten to pkgs/<leaf>, regardless of
	// whether the facade actually exists.
	assertContains(t, got, `"example.com/mod/pkgs/shared"`)
	assertNotContains(t, got, `"example.com/mod/internal/0/shared"`)

	// The facade directory for the dangling dep was NOT created — only
	// widget's directory exists.
	if _, err := os.Stat(filepath.Join(tmpDir, "pkgs", "shared")); !os.IsNotExist(err) {
		t.Errorf("pkgs/shared should not exist (dangling dep), err=%v", err)
	}
	if _, err := os.Stat(filepath.Join(tmpDir, "pkgs", "widget")); err != nil {
		t.Errorf("pkgs/widget should exist, err=%v", err)
	}
}

// TestExportCopyLibraryNoDanglingImports is the happy-path companion:
// --copy + --library exports every internal package, so the rewritten
// imports always resolve. Sanity-checks that running both flags
// together produces a coherent pkgs/ tree.
func TestExportCopyLibraryNoDanglingImports(t *testing.T) {
	tmpDir := t.TempDir()

	if err := os.WriteFile(filepath.Join(tmpDir, "go.mod"),
		[]byte("module example.com/mod\n\ngo 1.23\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	depDir := filepath.Join(tmpDir, "internal", "0", "shared")
	if err := os.MkdirAll(depDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(depDir, "shared.go"), []byte(`package shared

type Token struct{ V string }
`), 0o644); err != nil {
		t.Fatal(err)
	}

	pkgDir := filepath.Join(tmpDir, "internal", "alfa", "widget")
	if err := os.MkdirAll(pkgDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(pkgDir, "widget.go"), []byte(`package widget

import "example.com/mod/internal/0/shared"

func Stringify(t shared.Token) string { return t.V }
`), 0o644); err != nil {
		t.Fatal(err)
	}

	exporter := &Exporter{
		ModulePath:          "example.com/mod",
		Dir:                 tmpDir,
		OutputDir:           "pkgs",
		SkipConsumerRewrite: true,
		Env:                 append(os.Environ(), "GOWORK=off"),
		Copy:                true,
	}

	if err := exporter.ExportAll(); err != nil {
		t.Fatal(err)
	}

	// Both facades exist.
	for _, leaf := range []string{"shared", "widget"} {
		if _, err := os.Stat(filepath.Join(tmpDir, "pkgs", leaf)); err != nil {
			t.Errorf("pkgs/%s should exist after --library --copy, err=%v", leaf, err)
		}
	}

	// Widget's rewritten import resolves to the (now-present) shared facade.
	out, err := os.ReadFile(filepath.Join(tmpDir, "pkgs", "widget", "widget.go"))
	if err != nil {
		t.Fatalf("pkgs/widget/widget.go not generated: %v", err)
	}
	assertContains(t, string(out), `"example.com/mod/pkgs/shared"`)
}

// TestExportCopyGeneratedCompiles verifies that the copied pkgs/ tree
// is a real package that compiles. Catches import-rewrite bugs that
// text-only assertions miss.
func TestExportCopyGeneratedCompiles(t *testing.T) {
	tmpDir := t.TempDir()

	if err := os.WriteFile(filepath.Join(tmpDir, "go.mod"),
		[]byte("module example.com/mod\n\ngo 1.23\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	depDir := filepath.Join(tmpDir, "internal", "0", "shared")
	if err := os.MkdirAll(depDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(depDir, "shared.go"), []byte(`package shared

type Token struct{ V string }
`), 0o644); err != nil {
		t.Fatal(err)
	}

	pkgDir := filepath.Join(tmpDir, "internal", "alfa", "widget")
	if err := os.MkdirAll(pkgDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(pkgDir, "widget.go"), []byte(`package widget

import "example.com/mod/internal/0/shared"

func Stringify(t shared.Token) string { return t.V }
`), 0o644); err != nil {
		t.Fatal(err)
	}

	exporter := &Exporter{
		ModulePath:          "example.com/mod",
		Dir:                 tmpDir,
		OutputDir:           "pkgs",
		SkipConsumerRewrite: true,
		Env:                 append(os.Environ(), "GOWORK=off"),
		Copy:                true,
	}

	if err := exporter.ExportPackage("./internal/0/shared"); err != nil {
		t.Fatal(err)
	}
	if err := exporter.ExportPackage("./internal/alfa/widget"); err != nil {
		t.Fatal(err)
	}

	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedTypes | packages.NeedFiles,
		Dir:  tmpDir,
		Env:  append(os.Environ(), "GOWORK=off"),
	}
	loaded, err := packages.Load(cfg, "./pkgs/...")
	if err != nil {
		t.Fatalf("loading generated pkgs: %v", err)
	}
	for _, pkg := range loaded {
		for _, e := range pkg.Errors {
			t.Errorf("package %s: %v", pkg.PkgPath, e)
		}
	}
}
