package dagnabit

import (
	buildinfo "code.linenisgreat.com/purse-first/libs/dewey/internal/0/buildinfo"
)

// generatedHeaderText is the "Code generated by dagnabit" line stamped
// into every facade file the exporter produces. It carries the dagnabit
// build identity (version+commit from buildinfo, ldflags-injected by the
// nix build; "dev+unknown" otherwise) so a binary↔library version skew —
// a stale dagnabit run against a newer dewey — surfaces as drift in the
// generated output rather than staying silent until a compile error
// (purse-first#164, mirroring tommy#125).
//
// The value is stable build-to-build for a given binary (no timestamp,
// no per-run nonce), so committed facades regenerated by the same binary
// stay byte-identical and the `dagnabit export --check` drift guard
// stays green.
func generatedHeaderText() string {
	return "Code generated by dagnabit (" +
		buildinfo.Version + "+" + buildinfo.Commit +
		"); DO NOT EDIT."
}
