// Code generated by dagnabit; DO NOT EDIT.

package lua

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/charlie/lua"

type FunctionProto = internal.FunctionProto
type LBool = internal.LBool
type LFunction = internal.LFunction
type LGFunction = internal.LGFunction
type LState = internal.LState
type LString = internal.LString
type LTable = internal.LTable
type LValue = internal.LValue
type VM = internal.VM
type VMPool = internal.VMPool
type VMPoolBuilder = internal.VMPoolBuilder

var ClearTable = internal.ClearTable
var CompileReader = internal.CompileReader
var LNil = internal.LNil
var MakeVMPoolWithRequire = internal.MakeVMPoolWithRequire
var MakeVMPoolWithSearcher = internal.MakeVMPoolWithSearcher

const LTBool = internal.LTBool
const LTFunction = internal.LTFunction
const LTNil = internal.LTNil
const LTTable = internal.LTTable
const MultRet = internal.MultRet
