// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package lua

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/charlie/lua"

type (
	FunctionProto = internal.FunctionProto
	LBool         = internal.LBool
	LFunction     = internal.LFunction
	LGFunction    = internal.LGFunction
	LState        = internal.LState
	LString       = internal.LString
	LTable        = internal.LTable
	LValue        = internal.LValue
	VM            = internal.VM
	VMPool        = internal.VMPool
	VMPoolBuilder = internal.VMPoolBuilder
)

var (
	ClearTable             = internal.ClearTable
	CompileReader          = internal.CompileReader
	LNil                   = internal.LNil
	MakeVMPoolWithRequire  = internal.MakeVMPoolWithRequire
	MakeVMPoolWithSearcher = internal.MakeVMPoolWithSearcher
)

const (
	LTBool     = internal.LTBool
	LTFunction = internal.LTFunction
	LTNil      = internal.LTNil
	LTTable    = internal.LTTable
	MultRet    = internal.MultRet
)
