// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package script_value

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/echo/script_value"

type (
	ScriptValue = internal.ScriptValue
	Utility     = internal.Utility
)
