// Code generated by dagnabit; DO NOT EDIT.

package script_value

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/echo/script_value"

type (
	ScriptValue = internal.ScriptValue
	Utility     = internal.Utility
)
