// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package ohio_files

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/echo/ohio_files"

var (
	CopyFileLines         = internal.CopyFileLines
	CopyFileWithTransform = internal.CopyFileWithTransform
)
