// Code generated by dagnabit; DO NOT EDIT.

package ohio_files

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/echo/ohio_files"

var CopyFileLines = internal.CopyFileLines
var CopyFileWithTransform = internal.CopyFileWithTransform
