// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package pool

import (
	internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/alfa/pool"
	interfaces "github.com/amarbel-llc/purse-first/libs/dewey/pkgs/interfaces"
)

type (
	Bespoke[T any]                                         = internal.Bespoke[T]
	BespokeResetter[T any]                                 = internal.BespokeResetter[T]
	Pool[SWIMMER any, SWIMMER_PTR interfaces.Ptr[SWIMMER]] = internal.Pool[SWIMMER, SWIMMER_PTR]
	Slice[SWIMMER any, SWIMMER_SLICE interface {
		~[]SWIMMER
	}] = internal.Slice[SWIMMER, SWIMMER_SLICE]
)
type Value[SWIMMER any] = internal.Value[SWIMMER]

var (
	GetBufferedReader  = internal.GetBufferedReader
	GetBufferedWriter  = internal.GetBufferedWriter
	GetByteReader      = internal.GetByteReader
	GetSha256Hash      = internal.GetSha256Hash
	GetStringReader    = internal.GetStringReader
	OutstandingBorrows = internal.OutstandingBorrows
)

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func Make[SWIMMER any, SWIMMER_PTR interfaces.Ptr[SWIMMER]](New func() SWIMMER_PTR, Reset func(SWIMMER_PTR)) *internal.Pool[SWIMMER, SWIMMER_PTR] {
	return internal.Make[SWIMMER, SWIMMER_PTR](New, Reset)
}

func MakeSlice[SWIMMER any, SWIMMER_SLICE interface {
	~[]SWIMMER
}]() internal.Slice[SWIMMER, SWIMMER_SLICE] {
	return internal.MakeSlice[SWIMMER, SWIMMER_SLICE]()
}

func MakeValue[SWIMMER any](New func() SWIMMER, Reset func(SWIMMER)) *internal.Value[SWIMMER] {
	return internal.MakeValue[SWIMMER](New, Reset)
}

func MakeWithResetable[SWIMMER any, SWIMMER_PTR interfaces.ResetablePtr[SWIMMER]]() *internal.Pool[SWIMMER, SWIMMER_PTR] {
	return internal.MakeWithResetable[SWIMMER, SWIMMER_PTR]()
}
