// Code generated by dagnabit; DO NOT EDIT.

package pool

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/alfa/pool"

type (
	Bespoke[T any]         = internal.Bespoke[T]
	BespokeResetter[T any] = internal.BespokeResetter[T]
	Slice[SWIMMER any, SWIMMER_SLICE interface {
		~[]SWIMMER
	}] = internal.Slice[SWIMMER, SWIMMER_SLICE]
)

var (
	GetBufferedReader  = internal.GetBufferedReader
	GetBufferedWriter  = internal.GetBufferedWriter
	GetByteReader      = internal.GetByteReader
	GetSha256Hash      = internal.GetSha256Hash
	GetStringReader    = internal.GetStringReader
	OutstandingBorrows = internal.OutstandingBorrows
)

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func MakeSlice[SWIMMER any, SWIMMER_SLICE interface {
	~[]SWIMMER
}]() internal.Slice[SWIMMER, SWIMMER_SLICE] {
	return internal.MakeSlice[SWIMMER, SWIMMER_SLICE]()
}
