// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package delim_reader

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/charlie/delim_reader"

// Not safe for parallel use
type DelimReader = internal.DelimReader

var MakeDelimReader = internal.MakeDelimReader
