// Code generated by dagnabit; DO NOT EDIT.

package delim_reader

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/charlie/delim_reader"

type (
	DelimReader = internal.DelimReader
)

var (
	MakeDelimReader = internal.MakeDelimReader
)
