// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package delim_reader

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/charlie/delim_reader"

// Not safe for parallel use
type DelimReader = internal.DelimReader

var MakeDelimReader = internal.MakeDelimReader
