// Code generated by dagnabit; DO NOT EDIT.

package bech32

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/bech32"

var (
	Decode = internal.Decode
	Encode = internal.Encode
)
