// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package bech32

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/0/bech32"

// Decode decodes a Bech32 string. If the string is uppercase, the HRP will be uppercase.
var Decode = internal.Decode

// Encode encodes the HRP and a bytes slice to Bech32. If the HRP is uppercase,
// the output will be uppercase.
var Encode = internal.Encode
