// Code generated by dagnabit; DO NOT EDIT.

package analyzer_defererr

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/alfa/analyzer_defererr"

var (
	Analyzer = internal.Analyzer
)
