// Code generated by dagnabit; DO NOT EDIT.

package values

import (
	interfaces "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/interfaces"
	internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/charlie/values"
)

type (
	Bool        = internal.Bool
	Int         = internal.Int
	IntEqualer  = internal.IntEqualer
	IntLessor   = internal.IntLessor
	IntResetter = internal.IntResetter
	IntSlice    = internal.IntSlice
	String      = internal.String
	Uri         = internal.Uri
)

var (
	MakeBool          = internal.MakeBool
	MakeInt           = internal.MakeInt
	MakeString        = internal.MakeString
	MakeStringDefault = internal.MakeStringDefault
)

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func Equals[T interfaces.Equatable[T]](a T, b any) bool {
	return internal.Equals[T](a, b)
}
