// Code generated by dagnabit; DO NOT EDIT.

package values

import (
	internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/charlie/values"
	interfaces "github.com/amarbel-llc/purse-first/libs/dewey/pkgs/interfaces"
)

type Bool = internal.Bool
type Int = internal.Int
type IntEqualer = internal.IntEqualer
type IntLessor = internal.IntLessor
type IntResetter = internal.IntResetter
type IntSlice = internal.IntSlice
type String = internal.String
type Uri = internal.Uri

var MakeBool = internal.MakeBool
var MakeInt = internal.MakeInt
var MakeString = internal.MakeString
var MakeStringDefault = internal.MakeStringDefault

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func Equals[T interfaces.Equatable[T]](a T, b any) bool {
	return internal.Equals[T](a, b)
}
