// Code generated by dagnabit; DO NOT EDIT.

package collections_ptr

import (
	internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/delta/collections_ptr"
	interfaces "github.com/amarbel-llc/purse-first/libs/dewey/pkgs/interfaces"
)

// TODO-P2 add Resetter2 and Pool
type (
	Flag[VALUE interfaces.Value, VALUE_PTR interfaces.ValuePtr[VALUE]] = internal.Flag[VALUE, VALUE_PTR]
	MutableSet[T any, TPtr interfaces.Ptr[T]]                          = internal.MutableSet[T, TPtr]
	Set[T any, TPtr interfaces.Ptr[T]]                                 = internal.Set[T, TPtr]
	SetterPolicy                                                       = internal.SetterPolicy
)

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func MakeFlagCommas[VALUE interfaces.Value, VALUE_PTR interfaces.ValuePtr[VALUE]](policy internal.SetterPolicy) internal.Flag[VALUE, VALUE_PTR] {
	return internal.MakeFlagCommas[VALUE, VALUE_PTR](policy)
}

func MakeMutableSet[ELEMENT any, ELEMENT_PTR interfaces.Ptr[ELEMENT]](keyer interfaces.StringKeyerPtr[ELEMENT, ELEMENT_PTR], es ...ELEMENT_PTR) (s internal.MutableSet[ELEMENT, ELEMENT_PTR]) {
	return internal.MakeMutableSet[ELEMENT, ELEMENT_PTR](keyer, es...)
}

// constructs a mutable set of values using the given pointers
func MakeMutableValueSet[ELEMENT interfaces.Stringer, ELEMENT_PTR interfaces.StringerPtr[ELEMENT]](keyer interfaces.StringKeyerPtr[ELEMENT, ELEMENT_PTR], es ...ELEMENT_PTR) (s internal.MutableSet[ELEMENT, ELEMENT_PTR]) {
	return internal.MakeMutableValueSet[ELEMENT, ELEMENT_PTR](keyer, es...)
}

// constructs a mutable set of values using the given pointers
func MakeMutableValueSetValue[ELEMENT interfaces.Stringer, ELEMENT_PTR interfaces.StringerPtr[ELEMENT]](keyer interfaces.StringKeyerPtr[ELEMENT, ELEMENT_PTR], es ...ELEMENT) (s internal.MutableSet[ELEMENT, ELEMENT_PTR]) {
	return internal.MakeMutableValueSetValue[ELEMENT, ELEMENT_PTR](keyer, es...)
}

func MakeSet[ELEMENT any, ELEMENT_PTR interfaces.Ptr[ELEMENT]](keyer interfaces.StringKeyerPtr[ELEMENT, ELEMENT_PTR], es ...ELEMENT_PTR) (s internal.Set[ELEMENT, ELEMENT_PTR]) {
	return internal.MakeSet[ELEMENT, ELEMENT_PTR](keyer, es...)
}

func MakeSetValue[ELEMENT any, ELEMENT_PTR interfaces.Ptr[ELEMENT]](keyer interfaces.StringKeyerPtr[ELEMENT, ELEMENT_PTR], es ...ELEMENT) (s internal.Set[ELEMENT, ELEMENT_PTR]) {
	return internal.MakeSetValue[ELEMENT, ELEMENT_PTR](keyer, es...)
}

func MakeValueSet[ELEMENT interfaces.Stringer, ELEMENT_PTR interfaces.StringerPtr[ELEMENT]](keyer interfaces.StringKeyerPtr[ELEMENT, ELEMENT_PTR], es ...ELEMENT_PTR) (s internal.Set[ELEMENT, ELEMENT_PTR]) {
	return internal.MakeValueSet[ELEMENT, ELEMENT_PTR](keyer, es...)
}

func MakeValueSetSeq[ELEMENT interfaces.Stringer, ELEMENT_PTR interfaces.StringerPtr[ELEMENT]](keyer interfaces.StringKeyerPtr[ELEMENT, ELEMENT_PTR], seq interfaces.Seq[ELEMENT_PTR], count int) (set internal.Set[ELEMENT, ELEMENT_PTR]) {
	return internal.MakeValueSetSeq[ELEMENT, ELEMENT_PTR](keyer, seq, count)
}

func MakeValueSetString[ELEMENT interfaces.Stringer, ELEMENT_PTR interfaces.StringSetterPtr[ELEMENT]](keyer interfaces.StringKeyerPtr[ELEMENT, ELEMENT_PTR], es ...string) (s internal.Set[ELEMENT, ELEMENT_PTR], err error) {
	return internal.MakeValueSetString[ELEMENT, ELEMENT_PTR](keyer, es...)
}

func MakeValueSetValue[ELEMENT interfaces.Stringer, ELEMENT_PTR interfaces.StringerPtr[ELEMENT]](keyer interfaces.StringKeyerPtr[ELEMENT, ELEMENT_PTR], es ...ELEMENT) (s internal.Set[ELEMENT, ELEMENT_PTR]) {
	return internal.MakeValueSetValue[ELEMENT, ELEMENT_PTR](keyer, es...)
}

const (
	SetterPolicyAppend = internal.SetterPolicyAppend
	SetterPolicyReset  = internal.SetterPolicyReset
)
