// Code generated by dagnabit; DO NOT EDIT.

package collections_delta

import (
	interfaces "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/interfaces"
	internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/echo/collections_delta"
)

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func MakeSetDelta[ELEMENT interfaces.Stringer](from interfaces.Set[ELEMENT], to interfaces.Set[ELEMENT]) interfaces.Delta[ELEMENT] {
	return internal.MakeSetDelta[ELEMENT](from, to)
}
