// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package test_ui

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/alfa/test_ui"

type (
	TestCase[BLOB any] = internal.TestCase[BLOB]
	TestCaseInfo       = internal.TestCaseInfo
)

var (
	GetTestCaseDescription = internal.GetTestCaseDescription
	MakeTestCaseInfo       = internal.MakeTestCaseInfo
	PrintTestCaseInfo      = internal.PrintTestCaseInfo
)

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func MakeTestCase[BLOB any](name string, blob BLOB) internal.TestCase[BLOB] {
	return internal.MakeTestCase[BLOB](name, blob)
}

// MakeTestCaseCallerSkip is for re-export wrappers that add call frames.
func MakeTestCaseCallerSkip[BLOB any](name string, blob BLOB, callerSkip int) internal.TestCase[BLOB] {
	return internal.MakeTestCaseCallerSkip[BLOB](name, blob, callerSkip)
}
