// Code generated by dagnabit (dev+unknown); DO NOT EDIT.
//go:build test

package test_ui

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/alfa/test_ui"

type T = internal.T

var PrintDiffString = internal.PrintDiffString

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func TestPrintDiff[ELEMENT any](test *internal.T, a ELEMENT, b ELEMENT) {
	internal.TestPrintDiff[ELEMENT](test, a, b)
}
