// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package tridex

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/delta/tridex"

// TODO-P4 make generic
// TODO-P4 recycle nodes
// TODO-P4 confirm JSON structure is correct
// TODO switch to runes and rune readers as input
type Tridex = internal.Tridex

var Make = internal.Make
