// Code generated by dagnabit; DO NOT EDIT.

package tridex

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/delta/tridex"

type (
	Tridex = internal.Tridex
)

var (
	Make = internal.Make
)
