// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package analyzer_testui

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/alfa/analyzer_testui"

var Analyzer = internal.Analyzer
