// Code generated by dagnabit; DO NOT EDIT.

package collections_value

import (
	interfaces "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/interfaces"
	internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/delta/collections_value"
	"iter"
)

type (
	MutableSet[T any] = internal.MutableSet[T]
	Set[T any]        = internal.Set[T]
)

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func MakeMutableSet[ELEMENT any](keyer interfaces.StringKeyer[ELEMENT], count int, seq iter.Seq[ELEMENT]) (set internal.MutableSet[ELEMENT]) {
	return internal.MakeMutableSet[ELEMENT](keyer, count, seq)
}
func MakeMutableValueSet[ELEMENT interfaces.Stringer](keyer interfaces.StringKeyer[ELEMENT], elements ...ELEMENT) (set internal.MutableSet[ELEMENT]) {
	return internal.MakeMutableValueSet[ELEMENT](keyer, elements...)
}
func MakeSet[ELEMENT any](keyer interfaces.StringKeyer[ELEMENT], elements ...ELEMENT) (set internal.Set[ELEMENT]) {
	return internal.MakeSet[ELEMENT](keyer, elements...)
}
func MakeValueSet[ELEMENT interfaces.Stringer](keyer interfaces.StringKeyer[ELEMENT], seq iter.Seq[ELEMENT]) (set internal.Set[ELEMENT]) {
	return internal.MakeValueSet[ELEMENT](keyer, seq)
}
func MakeValueSetFromSlice[ELEMENT interfaces.Stringer](keyer interfaces.StringKeyer[ELEMENT], elements ...ELEMENT) (set internal.Set[ELEMENT]) {
	return internal.MakeValueSetFromSlice[ELEMENT](keyer, elements...)
}
func MakeValueSetValue[ELEMENT interfaces.Stringer](keyer interfaces.StringKeyer[ELEMENT], elements ...ELEMENT) (set internal.Set[ELEMENT]) {
	return internal.MakeValueSetValue[ELEMENT](keyer, elements...)
}
