// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package collections_value

import (
	internal "code.linenisgreat.com/purse-first/libs/dewey/internal/delta/collections_value"
	interfaces "code.linenisgreat.com/purse-first/libs/dewey/pkgs/interfaces"
)

type (
	MutableSet[T any] = internal.MutableSet[T]
	Set[T any]        = internal.Set[T]
)

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func MakeMutableSet[ELEMENT any](keyer interfaces.StringKeyer[ELEMENT], count int, seq interfaces.Seq[ELEMENT]) (set internal.MutableSet[ELEMENT]) {
	return internal.MakeMutableSet[ELEMENT](keyer, count, seq)
}

// TODO move construction to another derived package
func MakeMutableValueSet[ELEMENT interfaces.Stringer](keyer interfaces.StringKeyer[ELEMENT], elements ...ELEMENT) (set internal.MutableSet[ELEMENT]) {
	return internal.MakeMutableValueSet[ELEMENT](keyer, elements...)
}

func MakeSet[ELEMENT any](keyer interfaces.StringKeyer[ELEMENT], elements ...ELEMENT) (set internal.Set[ELEMENT]) {
	return internal.MakeSet[ELEMENT](keyer, elements...)
}

// TODO move construction to another derived package
func MakeValueSet[ELEMENT interfaces.Stringer](keyer interfaces.StringKeyer[ELEMENT], seq interfaces.Seq[ELEMENT]) (set internal.Set[ELEMENT]) {
	return internal.MakeValueSet[ELEMENT](keyer, seq)
}

func MakeValueSetFromSlice[ELEMENT interfaces.Stringer](keyer interfaces.StringKeyer[ELEMENT], elements ...ELEMENT) (set internal.Set[ELEMENT]) {
	return internal.MakeValueSetFromSlice[ELEMENT](keyer, elements...)
}

// TODO move construction to another derived package
func MakeValueSetValue[ELEMENT interfaces.Stringer](keyer interfaces.StringKeyer[ELEMENT], elements ...ELEMENT) (set internal.Set[ELEMENT]) {
	return internal.MakeValueSetValue[ELEMENT](keyer, elements...)
}
