// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package collections

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/delta/collections"

type (
	Bitset         = internal.Bitset
	KeyFunc[T any] = internal.KeyFunc[T]
)

var (
	MakeBitset   = internal.MakeBitset
	MakeBitsetOn = internal.MakeBitsetOn
	MakeKey      = internal.MakeKey
)

const MaxBitsetIdx = internal.MaxBitsetIdx
