// Code generated by dagnabit; DO NOT EDIT.

package collections

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/delta/collections"

type Bitset = internal.Bitset
type KeyFunc[T any] = internal.KeyFunc[T]

var MakeBitset = internal.MakeBitset
var MakeBitsetOn = internal.MakeBitsetOn
var MakeKey = internal.MakeKey

const MaxBitsetIdx = internal.MaxBitsetIdx
