// Code generated by dagnabit (dev+unknown); DO NOT EDIT.
//go:build debug

package errors

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/bravo/errors"

var PrintWithStackFramesIfNecessary = internal.PrintWithStackFramesIfNecessary
