// Code generated by dagnabit; DO NOT EDIT.

package errors

import (
	"io"

	internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/bravo/errors"
)

type (
	Context           = internal.Context
	ErrNotFound       = internal.ErrNotFound
	ErrorsIs          = internal.ErrorsIs
	Flusher           = internal.Flusher
	FuncContext       = internal.FuncContext
	FuncErr           = internal.FuncErr
	FuncIs            = internal.FuncIs
	FuncNil           = internal.FuncNil
	FuncWithStackInfo = internal.FuncWithStackInfo
	Group             = internal.Group
	GroupBuilder      = internal.GroupBuilder
)

// HTTPRenderer is the explicit transformer used at HTTP wire/UX boundaries
// to convert a domain error into its on-the-wire HTTP form. Domain code
// returns errors satisfying HTTPStatusCarrier; HTTP handlers/middleware
// call AsHTTPError(err) to obtain the rendered form.
type HTTPRenderer = internal.HTTPRenderer

// HTTPStatusCarrier is the semantic tag attached to errors that carry an
// HTTP status code. Detected via errors.As through wrapped chains.
type HTTPStatusCarrier = internal.HTTPStatusCarrier

// HTTPStatusError carries an HTTP status code as semantics, not identity.
// Error() returns the wrapped message, leaving the HTTP rendering to
// HTTPRender() / AsHTTPError() at the wire boundary. This means CLI tools,
// log lines, and other non-HTTP consumers get useful output without
// needing to walk past hidden-wrapper layers.
type (
	HTTPStatusError      = internal.HTTPStatusError
	Helpful              = internal.Helpful
	Signal               = internal.Signal
	Typed[DISAMB any]    = internal.Typed[DISAMB]
	UnwrapMany           = internal.UnwrapMany
	UnwrapOne            = internal.UnwrapOne
	WaitGroup            = internal.WaitGroup
	WithStackInfo[T any] = internal.WithStackInfo[T]
)

var As = internal.As

// AsHTTPError walks err's chain for an HTTPRenderer and returns the
// wire-shaped error. HTTP handlers call this to convert a domain error
// into the response shape. Returns (nil, false) if no HTTP-tagged
// error is in the chain.
var AsHTTPError = internal.AsHTTPError

// BadRequest tags an existing error with HTTP 400. No-op if the chain
// already carries 400.
var BadRequest = internal.BadRequest

// BadRequestWrapf is an alias for BadRequestf retained for backwards
// compatibility; both behave identically (pre-#107 they were already
// the same).
var BadRequestWrapf = internal.BadRequestWrapf

// BadRequestf formats and tags with HTTP 400.
var (
	BadRequestf              = internal.BadRequestf
	CancelWithNotImplemented = internal.CancelWithNotImplemented
)

// Conflictf formats and tags with HTTP 409.
var (
	Conflictf                               = internal.Conflictf
	ContextCancelWith499ClientClosedRequest = internal.ContextCancelWith499ClientClosedRequest
	ContextCancelWithBadRequestError        = internal.ContextCancelWithBadRequestError
	ContextCancelWithBadRequestf            = internal.ContextCancelWithBadRequestf
	ContextCancelWithError                  = internal.ContextCancelWithError
	ContextCancelWithErrorAndFormat         = internal.ContextCancelWithErrorAndFormat
	ContextCancelWithErrorf                 = internal.ContextCancelWithErrorf
	ContextCloseAfter                       = internal.ContextCloseAfter
	ContextContinueOrPanic                  = internal.ContextContinueOrPanic
	ContextFlushAfter                       = internal.ContextFlushAfter
	ContextMustClose                        = internal.ContextMustClose
	ContextMustFlush                        = internal.ContextMustFlush
	ContextSetCancelOnSIGHUP                = internal.ContextSetCancelOnSIGHUP
	ContextSetCancelOnSIGINT                = internal.ContextSetCancelOnSIGINT
	ContextSetCancelOnSIGTERM               = internal.ContextSetCancelOnSIGTERM
	Deferred                                = internal.Deferred
	DeferredCloseAndRename                  = internal.DeferredCloseAndRename
	DeferredCloser                          = internal.DeferredCloser
	DeferredFlusher                         = internal.DeferredFlusher
	DeferredRecover                         = internal.DeferredRecover
	Err400BadRequest                        = internal.Err400BadRequest
	Err405MethodNotAllowed                  = internal.Err405MethodNotAllowed
	Err409Conflict                          = internal.Err409Conflict
	Err422UnprocessableEntity               = internal.Err422UnprocessableEntity
	Err499ClientClosedRequest               = internal.Err499ClientClosedRequest
	Err500InternalServerError               = internal.Err500InternalServerError
	Err501NotImplemented                    = internal.Err501NotImplemented
	ErrExists                               = internal.ErrExists
	ErrorWithStackf                         = internal.ErrorWithStackf
	Errorf                                  = internal.Errorf
)

// GetErrNotFound extracts the ErrNotFound from an error chain.
// Returns the typed error and true if found, zero value and false otherwise.
var (
	GetErrNotFound = internal.GetErrNotFound
	Is             = internal.Is
)

// Is400BadRequest reports whether err's chain carries HTTP 400.
var Is400BadRequest = internal.Is400BadRequest

// Is499ClientClosedRequest reports whether err's chain carries HTTP 499.
var (
	Is499ClientClosedRequest = internal.Is499ClientClosedRequest
	IsAny                    = internal.IsAny
	IsBrokenPipe             = internal.IsBrokenPipe
	IsEOF                    = internal.IsEOF
	IsErrNotFound            = internal.IsErrNotFound
	IsErrno                  = internal.IsErrno
	IsExist                  = internal.IsExist
)

// IsHTTPError reports whether err's chain carries the given status code.
// Uses errors.As against the HTTPStatusCarrier interface so it works
// across both HTTPStatusError (domain) and httpRendering (wire).
var (
	IsHTTPError  = internal.IsHTTPError
	IsNetTimeout = internal.IsNetTimeout
	IsNotExist   = internal.IsNotExist
)

// TODO remove
var (
	IsNotNilAndNotEOF          = internal.IsNotNilAndNotEOF
	IsReadlinkInvalidArgument  = internal.IsReadlinkInvalidArgument
	IsSentinel                 = internal.IsSentinel
	IsStopIteration            = internal.IsStopIteration
	IsTooManyOpenFiles         = internal.IsTooManyOpenFiles
	IsWithTimeout              = internal.IsWithTimeout
	Join                       = internal.Join
	MakeContext                = internal.MakeContext
	MakeContextDefault         = internal.MakeContextDefault
	MakeErrNotFound            = internal.MakeErrNotFound
	MakeErrNotFoundString      = internal.MakeErrNotFoundString
	MakeErrStopIteration       = internal.MakeErrStopIteration
	MakeFuncContextFromFuncErr = internal.MakeFuncContextFromFuncErr
	MakeFuncContextFromFuncNil = internal.MakeFuncContextFromFuncNil
	MakeFuncErrFromFuncNil     = internal.MakeFuncErrFromFuncNil
)

// TODO consider making a pool and return a repool func on construction
var MakeGroupBuilder = internal.MakeGroupBuilder

// MakeHTTPStatusError constructs an HTTPStatusError directly. Prefer the
// status-specific constructors (BadRequestf, Conflictf, …) where
// possible.
var (
	MakeHTTPStatusError   = internal.MakeHTTPStatusError
	MakeIsErrno           = internal.MakeIsErrno
	MakeWaitGroupParallel = internal.MakeWaitGroupParallel
	MakeWaitGroupSerial   = internal.MakeWaitGroupSerial
	Must                  = internal.Must
)

// NotImplementedf formats and tags with HTTP 501.
var (
	NotImplementedf                = internal.NotImplementedf
	PanicIfError                   = internal.PanicIfError
	PrintHelpful                   = internal.PrintHelpful
	RunChildContextWithPrintTicker = internal.RunChildContextWithPrintTicker
	RunContextWithPrintTicker      = internal.RunContextWithPrintTicker
)

// UnprocessableEntityf formats and tags with HTTP 422.
var (
	UnprocessableEntityf = internal.UnprocessableEntityf
	Unwrap               = internal.Unwrap
	WithHelp             = internal.WithHelp
	WithoutStack         = internal.WithoutStack
	Wrap                 = internal.Wrap
)

// Wrap the error with stack info unless it's one of the provided `except`
// errors, in which case return that bare error. Direct value comparison is
// performed (`in == except`) rather than errors.Is.
var WrapExceptSentinel = internal.WrapExceptSentinel

// Wrap the error with stack info unless it's one of the provided `except`
// errors, in which case return nil. Direct value comparison is
// performed (`in == except`) rather than errors.Is.
var (
	WrapExceptSentinelAsNil = internal.WrapExceptSentinelAsNil
	WrapSkip                = internal.WrapSkip
	Wrapf                   = internal.Wrapf
)

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func DeferredYieldCloser[T any](yield func(T, error) bool, closer io.Closer) {
	internal.DeferredYieldCloser[T](yield, closer)
}

func IsTyped[DISAMB any](err error) bool {
	return internal.IsTyped[DISAMB](err)
}

// MakeTypedSentinel creates a typed sentinel error and its checker function.
// This is a convenience helper to reduce boilerplate when creating package errors.
//
// Usage:
//
//	type pkgErrDisamb struct{}
//	var (
//	    ErrMyError, IsMyError = errors.MakeTypedSentinel[pkgErrDisamb]("my error")
//	)
//
// The returned sentinel implements errors.Typed[DISAMB] and can be checked with
// either the returned checker function or errors.IsTyped[DISAMB](err).
func MakeTypedSentinel[DISAMB any](text string) (sentinel internal.Typed[DISAMB], check func(error) bool) {
	return internal.MakeTypedSentinel[DISAMB](text)
}

func NewWithType[DISAMB any](text string) internal.Typed[DISAMB] {
	return internal.NewWithType[DISAMB](text)
}

func WrapWithType[DISAMB any](err error) internal.Typed[DISAMB] {
	return internal.WrapWithType[DISAMB](err)
}
