// Code generated by dagnabit; DO NOT EDIT.

package errors

import (
	internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/bravo/errors"
	"io"
)

type (
	Context              = internal.Context
	ErrNotFound          = internal.ErrNotFound
	ErrorsIs             = internal.ErrorsIs
	Flusher              = internal.Flusher
	FuncContext          = internal.FuncContext
	FuncErr              = internal.FuncErr
	FuncIs               = internal.FuncIs
	FuncNil              = internal.FuncNil
	FuncWithStackInfo    = internal.FuncWithStackInfo
	Group                = internal.Group
	GroupBuilder         = internal.GroupBuilder
	Helpful              = internal.Helpful
	Signal               = internal.Signal
	Typed[DISAMB any]    = internal.Typed[DISAMB]
	UnwrapMany           = internal.UnwrapMany
	UnwrapOne            = internal.UnwrapOne
	WaitGroup            = internal.WaitGroup
	WithStackInfo[T any] = internal.WithStackInfo[T]
)

var (
	As                                      = internal.As
	BadRequest                              = internal.BadRequest
	BadRequestWrapf                         = internal.BadRequestWrapf
	BadRequestf                             = internal.BadRequestf
	CancelWithNotImplemented                = internal.CancelWithNotImplemented
	ContextCancelWith499ClientClosedRequest = internal.ContextCancelWith499ClientClosedRequest
	ContextCancelWithBadRequestError        = internal.ContextCancelWithBadRequestError
	ContextCancelWithBadRequestf            = internal.ContextCancelWithBadRequestf
	ContextCancelWithError                  = internal.ContextCancelWithError
	ContextCancelWithErrorAndFormat         = internal.ContextCancelWithErrorAndFormat
	ContextCancelWithErrorf                 = internal.ContextCancelWithErrorf
	ContextCloseAfter                       = internal.ContextCloseAfter
	ContextContinueOrPanic                  = internal.ContextContinueOrPanic
	ContextFlushAfter                       = internal.ContextFlushAfter
	ContextMustClose                        = internal.ContextMustClose
	ContextMustFlush                        = internal.ContextMustFlush
	ContextSetCancelOnSIGHUP                = internal.ContextSetCancelOnSIGHUP
	ContextSetCancelOnSIGINT                = internal.ContextSetCancelOnSIGINT
	ContextSetCancelOnSIGTERM               = internal.ContextSetCancelOnSIGTERM
	Deferred                                = internal.Deferred
	DeferredCloseAndRename                  = internal.DeferredCloseAndRename
	DeferredCloser                          = internal.DeferredCloser
	DeferredFlusher                         = internal.DeferredFlusher
	DeferredRecover                         = internal.DeferredRecover
	Err400BadRequest                        = internal.Err400BadRequest
	Err405MethodNotAllowed                  = internal.Err405MethodNotAllowed
	Err409Conflict                          = internal.Err409Conflict
	Err422UnprocessableEntity               = internal.Err422UnprocessableEntity
	Err499ClientClosedRequest               = internal.Err499ClientClosedRequest
	Err500InternalServerError               = internal.Err500InternalServerError
	Err501NotImplemented                    = internal.Err501NotImplemented
	ErrExists                               = internal.ErrExists
	ErrorWithStackf                         = internal.ErrorWithStackf
	Errorf                                  = internal.Errorf
	GetErrNotFound                          = internal.GetErrNotFound
	Is                                      = internal.Is
	Is400BadRequest                         = internal.Is400BadRequest
	Is499ClientClosedRequest                = internal.Is499ClientClosedRequest
	IsAny                                   = internal.IsAny
	IsBrokenPipe                            = internal.IsBrokenPipe
	IsEOF                                   = internal.IsEOF
	IsErrNotFound                           = internal.IsErrNotFound
	IsErrno                                 = internal.IsErrno
	IsExist                                 = internal.IsExist
	IsHTTPError                             = internal.IsHTTPError
	IsNetTimeout                            = internal.IsNetTimeout
	IsNotExist                              = internal.IsNotExist
	IsNotNilAndNotEOF                       = internal.IsNotNilAndNotEOF
	IsReadlinkInvalidArgument               = internal.IsReadlinkInvalidArgument
	IsSentinel                              = internal.IsSentinel
	IsStopIteration                         = internal.IsStopIteration
	IsTooManyOpenFiles                      = internal.IsTooManyOpenFiles
	IsWithTimeout                           = internal.IsWithTimeout
	Join                                    = internal.Join
	MakeContext                             = internal.MakeContext
	MakeContextDefault                      = internal.MakeContextDefault
	MakeErrNotFound                         = internal.MakeErrNotFound
	MakeErrNotFoundString                   = internal.MakeErrNotFoundString
	MakeErrStopIteration                    = internal.MakeErrStopIteration
	MakeFuncContextFromFuncErr              = internal.MakeFuncContextFromFuncErr
	MakeFuncContextFromFuncNil              = internal.MakeFuncContextFromFuncNil
	MakeFuncErrFromFuncNil                  = internal.MakeFuncErrFromFuncNil
	MakeGroupBuilder                        = internal.MakeGroupBuilder
	MakeIsErrno                             = internal.MakeIsErrno
	MakeWaitGroupParallel                   = internal.MakeWaitGroupParallel
	MakeWaitGroupSerial                     = internal.MakeWaitGroupSerial
	Must                                    = internal.Must
	PanicIfError                            = internal.PanicIfError
	PrintHelpful                            = internal.PrintHelpful
	PrintStackTracerIfNecessary             = internal.PrintStackTracerIfNecessary
	RunChildContextWithPrintTicker          = internal.RunChildContextWithPrintTicker
	RunContextWithPrintTicker               = internal.RunContextWithPrintTicker
	Unwrap                                  = internal.Unwrap
	WithHelp                                = internal.WithHelp
	WithoutStack                            = internal.WithoutStack
	Wrap                                    = internal.Wrap
	WrapExceptSentinel                      = internal.WrapExceptSentinel
	WrapExceptSentinelAsNil                 = internal.WrapExceptSentinelAsNil
	WrapSkip                                = internal.WrapSkip
	Wrapf                                   = internal.Wrapf
)

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func DeferredYieldCloser[T any](yield func(T, error) bool, closer io.Closer) {
	internal.DeferredYieldCloser[T](yield, closer)
}
func IsTyped[DISAMB any](err error) bool {
	return internal.IsTyped[DISAMB](err)
}
func MakeTypedSentinel[DISAMB any](text string) (sentinel internal.Typed[DISAMB], check func(error) bool) {
	return internal.MakeTypedSentinel[DISAMB](text)
}
func NewWithType[DISAMB any](text string) internal.Typed[DISAMB] {
	return internal.NewWithType[DISAMB](text)
}
func WrapWithType[DISAMB any](err error) internal.Typed[DISAMB] {
	return internal.WrapWithType[DISAMB](err)
}
