// Code generated by dagnabit; DO NOT EDIT.
//go:build !debug

package errors

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/bravo/errors"

var (
	PrintStackTracerIfNecessary = internal.PrintStackTracerIfNecessary
)
