// Code generated by dagnabit (dev+unknown); DO NOT EDIT.
//go:build !debug

package errors

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/bravo/errors"

var PrintStackTracerIfNecessary = internal.PrintStackTracerIfNecessary
