// Code generated by dagnabit; DO NOT EDIT.

package cmp

import (
	"cmp"

	internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/alfa/cmp"
	interfaces "github.com/amarbel-llc/purse-first/libs/dewey/pkgs/interfaces"
)

type (
	ComparableBytes            = internal.ComparableBytes
	ComparableString           = internal.ComparableString
	Equaler[ELEMENT any]       = internal.Equaler[ELEMENT]
	EqualerVerify[ELEMENT any] = internal.EqualerVerify[ELEMENT]
	Func[ELEMENT any]          = internal.Func[ELEMENT]
	Lesser[ELEMENT any]        = internal.Lesser[ELEMENT]
	LesserVerify[ELEMENT any]  = internal.LesserVerify[ELEMENT]
	Result                     = internal.Result
)

var (
	Bytes                     = internal.Bytes
	CompareUTF8Bytes          = internal.CompareUTF8Bytes
	CompareUTF8BytesAndString = internal.CompareUTF8BytesAndString
	CompareUTF8String         = internal.CompareUTF8String
	CompareUTF8StringAndBytes = internal.CompareUTF8StringAndBytes
	String                    = internal.String
)

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func BinarySearchFuncElement[SLICE interface {
	~[]ELEMENT
}, ELEMENT any, TARGET any](slice SLICE, target TARGET, cmp func(ELEMENT, TARGET) internal.Result) (element ELEMENT, ok bool) {
	return internal.BinarySearchFuncElement[SLICE, ELEMENT, TARGET](slice, target, cmp)
}

func BinarySearchFuncIndex[SLICE interface {
	~[]ELEMENT
}, ELEMENT any, TARGET any](slice SLICE, target TARGET, cmp func(ELEMENT, TARGET) internal.Result) (int, bool) {
	return internal.BinarySearchFuncIndex[SLICE, ELEMENT, TARGET](slice, target, cmp)
}

func CompareUTF8[LEFT interfaces.Comparable[LEFT], RIGHT interfaces.Comparable[RIGHT]](left LEFT, right RIGHT, partial bool) internal.Result {
	return internal.CompareUTF8[LEFT, RIGHT](left, right, partial)
}

// TODO remove
func MakeFuncFromEqualerAndLessor3EqualFirst[ELEMENT any](equaler interfaces.Equaler[ELEMENT], lessor interfaces.Lessor[ELEMENT]) func(ELEMENT, ELEMENT) internal.Result {
	return internal.MakeFuncFromEqualerAndLessor3EqualFirst[ELEMENT](equaler, lessor)
}

// TODO remove
func MakeFuncFromEqualerAndLessor3LessFirst[ELEMENT any](equaler interfaces.Equaler[ELEMENT], lessor interfaces.Lessor[ELEMENT]) func(ELEMENT, ELEMENT) internal.Result {
	return internal.MakeFuncFromEqualerAndLessor3LessFirst[ELEMENT](equaler, lessor)
}

func Ordered[ELEMENT cmp.Ordered](left ELEMENT, right ELEMENT) internal.Result {
	return internal.Ordered[ELEMENT](left, right)
}

const (
	Equal   = internal.Equal
	Greater = internal.Greater
	Less    = internal.Less
)
