// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package age

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/echo/age"

type (
	Identity             = internal.Identity
	MultiIdentity        = internal.MultiIdentity
	NoIdentityMatchError = internal.NoIdentityMatchError
	Recipient            = internal.Recipient
	Recipients           = internal.Recipients
)

var (
	IsNoIdentityMatchError = internal.IsNoIdentityMatchError
	MakeMultiIdentity      = internal.MakeMultiIdentity
)
