// Code generated by dagnabit; DO NOT EDIT.

package age

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/echo/age"

type Identity = internal.Identity
type MultiIdentity = internal.MultiIdentity
type NoIdentityMatchError = internal.NoIdentityMatchError
type Recipient = internal.Recipient
type Recipients = internal.Recipients

var IsNoIdentityMatchError = internal.IsNoIdentityMatchError
var MakeMultiIdentity = internal.MakeMultiIdentity
