// Code generated by dagnabit; DO NOT EDIT.

package primordial

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/primordial"

var (
	IsTTY = internal.IsTTY
	IsTty = internal.IsTty
)
