// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package primordial

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/0/primordial"

var IsTTY = internal.IsTTY

// Deprecated: use IsTTY.
var IsTty = internal.IsTty
