// Code generated by dagnabit; DO NOT EDIT.

package operation_viewport

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/charlie/operation_viewport"

type (
	Batch             = internal.Batch
	BatchDone         = internal.BatchDone
	Emitter           = internal.Emitter
	LogLine           = internal.LogLine
	Model             = internal.Model
	Op                = internal.Op
	OperationDone     = internal.OperationDone
	OperationProgress = internal.OperationProgress
	OperationStarted  = internal.OperationStarted
	Option            = internal.Option
	Style             = internal.Style
)

var (
	DefaultStyle = internal.DefaultStyle
	NewModel     = internal.NewModel
	Run          = internal.Run
	RunBatch     = internal.RunBatch
	WithLines    = internal.WithLines
	WithStyle    = internal.WithStyle
	WithTitle    = internal.WithTitle
	WithTotal    = internal.WithTotal
)
