// Code generated by dagnabit; DO NOT EDIT.

package delim_io

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/delta/delim_io"

type (
	Reader = internal.Reader
)

var (
	CopyWithPrefixOnDelim = internal.CopyWithPrefixOnDelim
	Make                  = internal.Make
)
