// Code generated by dagnabit; DO NOT EDIT.

package collections_slice

import (
	internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/bravo/collections_slice"
	cmp "github.com/amarbel-llc/purse-first/libs/dewey/pkgs/cmp"
	interfaces "github.com/amarbel-llc/purse-first/libs/dewey/pkgs/interfaces"
)

type Byte = internal.Byte
type Rune = internal.Rune
type Slice[ELEMENT any] = internal.Slice[ELEMENT]
type String = internal.String

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func Collect[ELEMENT any](seq interfaces.Seq[ELEMENT]) internal.Slice[ELEMENT] {
	return internal.Collect[ELEMENT](seq)
}
func Make[ELEMENT any](elements ...ELEMENT) internal.Slice[ELEMENT] {
	return internal.Make[ELEMENT](elements...)
}
func MakeFromSeq[ELEMENT any](count int, seq interfaces.Seq[ELEMENT]) internal.Slice[ELEMENT] {
	return internal.MakeFromSeq[ELEMENT](count, seq)
}
func MakeFromSlice[ELEMENT any](elements ...ELEMENT) internal.Slice[ELEMENT] {
	return internal.MakeFromSlice[ELEMENT](elements...)
}
func MakeWithCap[ELEMENT any](capacity int) internal.Slice[ELEMENT] {
	return internal.MakeWithCap[ELEMENT](capacity)
}
func MakeWithLen[ELEMENT any](length int) internal.Slice[ELEMENT] {
	return internal.MakeWithLen[ELEMENT](length)
}
func SortedValues[ELEMENT interfaces.Value](seq interfaces.Seq[ELEMENT]) []ELEMENT {
	return internal.SortedValues[ELEMENT](seq)
}
func SortedValuesBy[ELEMENT any](collection interfaces.Collection[ELEMENT], cmpFunc cmp.Func[ELEMENT]) []ELEMENT {
	return internal.SortedValuesBy[ELEMENT](collection, cmpFunc)
}
