// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package ohio_buffer

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/charlie/ohio_buffer"

var (
	Copy          = internal.Copy
	MakeErrLength = internal.MakeErrLength
)
