// Code generated by dagnabit; DO NOT EDIT.

package ohio_buffer

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/charlie/ohio_buffer"

var (
	Copy          = internal.Copy
	MakeErrLength = internal.MakeErrLength
)
