// Code generated by dagnabit; DO NOT EDIT.

package http_statuses

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/http_statuses"

type Code = internal.Code

const Code400BadRequest = internal.Code400BadRequest
const Code405MethodNotAllowed = internal.Code405MethodNotAllowed
const Code409Conflict = internal.Code409Conflict
const Code422UnprocessableEntity = internal.Code422UnprocessableEntity
const Code499ClientClosedRequest = internal.Code499ClientClosedRequest
const Code500InternalServerError = internal.Code500InternalServerError
const Code501NotImplemented = internal.Code501NotImplemented
