// Code generated by dagnabit; DO NOT EDIT.

package http_statuses

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/http_statuses"

type Code = internal.Code

const (
	Code400BadRequest          = internal.Code400BadRequest
	Code405MethodNotAllowed    = internal.Code405MethodNotAllowed
	Code409Conflict            = internal.Code409Conflict
	Code422UnprocessableEntity = internal.Code422UnprocessableEntity
	Code499ClientClosedRequest = internal.Code499ClientClosedRequest
	Code500InternalServerError = internal.Code500InternalServerError
	Code501NotImplemented      = internal.Code501NotImplemented
)
