// Code generated by dagnabit; DO NOT EDIT.

package config_cli

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/foxtrot/config_cli"

type (
	Config = internal.Config
)

var (
	Default = internal.Default
	FromAny = internal.FromAny
)
