// Code generated by dagnabit; DO NOT EDIT.

package command

import (
	interfaces "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/interfaces"
	internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/echo/command"
	"iter"
)

type (
	Arg[V interfaces.FlagValue]  = internal.Arg[V]
	ArrayFlag                    = internal.ArrayFlag
	BoolFlag                     = internal.BoolFlag
	CLICompleter                 = internal.CLICompleter
	Cmd                          = internal.Cmd
	Command                      = internal.Command
	CommandComponent             = internal.CommandComponent
	CommandComponentReader       = internal.CommandComponentReader
	CommandLineInput             = internal.CommandLineInput
	CommandWithDescription       = internal.CommandWithDescription
	CommandWithMCPAnnotations    = internal.CommandWithMCPAnnotations
	CommandWithParams            = internal.CommandWithParams
	CommandWithResult            = internal.CommandWithResult
	Completer                    = internal.Completer
	Completion                   = internal.Completion
	Description                  = internal.Description
	EnvVar                       = internal.EnvVar
	Example                      = internal.Example
	FilePath                     = internal.FilePath
	Flag[V interfaces.FlagValue] = internal.Flag[V]
	FlagValueCompleter           = internal.FlagValueCompleter
	FuncCompleter                = internal.FuncCompleter
	IntArg                       = internal.IntArg
	IntFlag                      = internal.IntFlag
	MCPAnnotations               = internal.MCPAnnotations
	ManpageFile                  = internal.ManpageFile
	ObjectFlag                   = internal.ObjectFlag
	OldArg                       = internal.OldArg
	OldParam                     = internal.OldParam
	Param                        = internal.Param
	ParamCompleter               = internal.ParamCompleter
	ParamType                    = internal.ParamType
	Prompter                     = internal.Prompter
	Request                      = internal.Request
	Result                       = internal.Result
	StringArg                    = internal.StringArg
	StringFlag                   = internal.StringFlag
	StubPrompter                 = internal.StubPrompter
	SupportsCompletion           = internal.SupportsCompletion
	ToolMapping                  = internal.ToolMapping
	Utility                      = internal.Utility
)

var (
	FindToolMatch       = internal.FindToolMatch
	JSONResult          = internal.JSONResult
	NewUtility          = internal.NewUtility
	PopRequestArgTo     = internal.PopRequestArgTo
	PopRequestArgToFunc = internal.PopRequestArgToFunc
	TextErrorResult     = internal.TextErrorResult
	TextResult          = internal.TextResult
)

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func PopRequestArg[VALUE interfaces.Stringer, VALUE_PTR interfaces.StringerSetterPtr[VALUE]](req internal.Request, name string) VALUE_PTR {
	return internal.PopRequestArg[VALUE, VALUE_PTR](req, name)
}
func PopRequestArgs[VALUE interfaces.Stringer, VALUE_PTR interfaces.StringerSetterPtr[VALUE]](req internal.Request, name string) iter.Seq[VALUE_PTR] {
	return internal.PopRequestArgs[VALUE, VALUE_PTR](req, name)
}

const (
	Array  = internal.Array
	Bool   = internal.Bool
	Float  = internal.Float
	Int    = internal.Int
	Object = internal.Object
	String = internal.String
)
