// Code generated by dagnabit; DO NOT EDIT.

package flags

import (
	interfaces "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/interfaces"
	internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/charlie/flags"
	"iter"
)

type (
	Definitions     = internal.Definitions
	ErrInvalidValue = internal.ErrInvalidValue
	ErrorHandling   = internal.ErrorHandling
	Flag            = internal.Flag
	FlagSet         = internal.FlagSet
	FlagWithPolicy  = internal.FlagWithPolicy
	Getter          = internal.Getter
)

var (
	Arg                = internal.Arg
	Args               = internal.Args
	Bool               = internal.Bool
	BoolFunc           = internal.BoolFunc
	BoolVar            = internal.BoolVar
	CommandLine        = internal.CommandLine
	Duration           = internal.Duration
	DurationVar        = internal.DurationVar
	ErrHelp            = internal.ErrHelp
	Float64            = internal.Float64
	Float64Var         = internal.Float64Var
	Func               = internal.Func
	Int                = internal.Int
	Int64              = internal.Int64
	Int64Var           = internal.Int64Var
	IntVar             = internal.IntVar
	Lookup             = internal.Lookup
	MakeWithPolicy     = internal.MakeWithPolicy
	NArg               = internal.NArg
	NFlag              = internal.NFlag
	NewFlagSet         = internal.NewFlagSet
	Parse              = internal.Parse
	Parsed             = internal.Parsed
	PrintDefaults      = internal.PrintDefaults
	Set                = internal.Set
	SplitCommasAndTrim = internal.SplitCommasAndTrim
	String             = internal.String
	StringVar          = internal.StringVar
	TextVar            = internal.TextVar
	Uint               = internal.Uint
	Uint64             = internal.Uint64
	Uint64Var          = internal.Uint64Var
	UintVar            = internal.UintVar
	UnquoteUsage       = internal.UnquoteUsage
	Usage              = internal.Usage
	Var                = internal.Var
	Visit              = internal.Visit
	VisitAll           = internal.VisitAll
)

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func SplitCommasAndTrimAndMake[ELEMENT interfaces.Value, ELEMENT_PTR interfaces.ValuePtr[ELEMENT]](value string) iter.Seq2[ELEMENT, error] {
	return internal.SplitCommasAndTrimAndMake[ELEMENT, ELEMENT_PTR](value)
}

const (
	ContinueOnError = internal.ContinueOnError
	ExitOnError     = internal.ExitOnError
	PanicOnError    = internal.PanicOnError
)
