// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package box_chars

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/box_chars"

const (
	ElbowBottomRight = internal.ElbowBottomRight
	ElbowLeftBottom  = internal.ElbowLeftBottom
)

// elbows
const (
	ElbowTopRight  = internal.ElbowTopRight
	PipeHorizontal = internal.PipeHorizontal
)

// pipes
const (
	PipeVertical = internal.PipeVertical
	TeeBottom    = internal.TeeBottom
)

// tees
const TeeRight = internal.TeeRight
