// Code generated by dagnabit; DO NOT EDIT.

package box_chars

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/box_chars"

const ElbowBottomRight = internal.ElbowBottomRight
const ElbowLeftBottom = internal.ElbowLeftBottom

// elbows
const ElbowTopRight = internal.ElbowTopRight
const PipeHorizontal = internal.PipeHorizontal

// pipes
const PipeVertical = internal.PipeVertical
const TeeBottom = internal.TeeBottom

// tees
const TeeRight = internal.TeeRight
