// Code generated by dagnabit; DO NOT EDIT.

package box_chars

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/box_chars"

const (
	ElbowBottomRight = internal.ElbowBottomRight
	ElbowLeftBottom  = internal.ElbowLeftBottom
	ElbowTopRight    = internal.ElbowTopRight
	PipeHorizontal   = internal.PipeHorizontal
	PipeVertical     = internal.PipeVertical
	TeeBottom        = internal.TeeBottom
	TeeRight         = internal.TeeRight
)
