package dagnabit

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateFacadeTypesOnly(t *testing.T) {
	symbols := ExportedSymbols{
		Types: []TypeSymbol{
			{Name: "Config"},
			{Name: "Reader"},
		},
	}

	got := string(generateFacade("mypackage", "example.com/mod/internal/alfa/mypackage", symbols))

	assertContains(t, got, "// Code generated by dagnabit; DO NOT EDIT.")
	assertContains(t, got, "package mypackage")
	assertContains(t, got, `internal "example.com/mod/internal/alfa/mypackage"`)
	assertContains(t, got, "Config = internal.Config")
	assertContains(t, got, "Reader = internal.Reader")
	assertNotContains(t, got, "var (")
	assertNotContains(t, got, "const (")
}

func TestGenerateFacadeVarsOnly(t *testing.T) {
	symbols := ExportedSymbols{
		Vars: []string{"MakeReader", "DefaultConfig"},
	}

	got := string(generateFacade("mypackage", "example.com/mod/internal/alfa/mypackage", symbols))

	assertContains(t, got, "DefaultConfig = internal.DefaultConfig")
	assertContains(t, got, "MakeReader    = internal.MakeReader")
	assertNotContains(t, got, "type (")
}

func TestGenerateFacadeConstsOnly(t *testing.T) {
	symbols := ExportedSymbols{
		Consts: []string{"MaxRetries", "DefaultTimeout"},
	}

	got := string(generateFacade("mypackage", "example.com/mod/internal/alfa/mypackage", symbols))

	assertContains(t, got, "const (")
	assertContains(t, got, "DefaultTimeout = internal.DefaultTimeout")
	assertContains(t, got, "MaxRetries     = internal.MaxRetries")
}

func TestGenerateFacadeGenericType(t *testing.T) {
	symbols := ExportedSymbols{
		Types: []TypeSymbol{
			{Name: "Pool", TypeParams: "[T any]", TypeArgs: "[T]"},
		},
	}

	got := string(generateFacade("mypackage", "example.com/mod/internal/alfa/mypackage", symbols))

	assertContains(t, got, "Pool[T any] = internal.Pool[T]")
}

func TestGenerateFacadeMixed(t *testing.T) {
	symbols := ExportedSymbols{
		Types: []TypeSymbol{
			{Name: "Writer"},
		},
		Vars:   []string{"NewWriter"},
		Consts: []string{"MaxSize"},
	}

	got := string(generateFacade("mypackage", "example.com/mod/internal/alfa/mypackage", symbols))

	assertContains(t, got, "type (")
	assertContains(t, got, "var (")
	assertContains(t, got, "const (")
}

func TestEnumerateExportedSymbolsAreSorted(t *testing.T) {
	// enumerateExportedSymbols sorts its output; generateFacade trusts the
	// caller to provide pre-sorted input. This test verifies the contract
	// by passing pre-sorted symbols and checking order is preserved.
	symbols := ExportedSymbols{
		Types: []TypeSymbol{
			{Name: "Alpha"},
			{Name: "Middle"},
			{Name: "Zebra"},
		},
	}

	got := string(generateFacade("mypackage", "example.com/mod/internal/alfa/mypackage", symbols))

	alphaIdx := strings.Index(got, "Alpha")
	middleIdx := strings.Index(got, "Middle")
	zebraIdx := strings.Index(got, "Zebra")

	if alphaIdx >= middleIdx || middleIdx >= zebraIdx {
		t.Errorf("types not in expected order:\n%s", got)
	}
}

func TestScanForExportDirectives(t *testing.T) {
	tmpDir := t.TempDir()

	// Create a package with the directive
	pkgDir := filepath.Join(tmpDir, "internal", "alfa", "has_directive")
	if err := os.MkdirAll(pkgDir, 0o755); err != nil {
		t.Fatal(err)
	}

	if err := os.WriteFile(
		filepath.Join(pkgDir, "main.go"),
		[]byte("package has_directive\n\n//go:generate dagnabit export\n\ntype Foo struct{}\n"),
		0o644,
	); err != nil {
		t.Fatal(err)
	}

	// Create a package without the directive
	noDirPkg := filepath.Join(tmpDir, "internal", "bravo", "no_directive")
	if err := os.MkdirAll(noDirPkg, 0o755); err != nil {
		t.Fatal(err)
	}

	if err := os.WriteFile(
		filepath.Join(noDirPkg, "main.go"),
		[]byte("package no_directive\n\ntype Bar struct{}\n"),
		0o644,
	); err != nil {
		t.Fatal(err)
	}

	dirs, err := scanForExportDirectives(filepath.Join(tmpDir, "internal"))
	if err != nil {
		t.Fatal(err)
	}

	if len(dirs) != 1 {
		t.Fatalf("expected 1 directory, got %d: %v", len(dirs), dirs)
	}

	if dirs[0] != pkgDir {
		t.Errorf("expected %s, got %s", pkgDir, dirs[0])
	}
}

func TestFileContainsDirective(t *testing.T) {
	tmpDir := t.TempDir()

	withDirective := filepath.Join(tmpDir, "with.go")
	if err := os.WriteFile(withDirective, []byte("package foo\n\n//go:generate dagnabit export\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	withoutDirective := filepath.Join(tmpDir, "without.go")
	if err := os.WriteFile(withoutDirective, []byte("package foo\n\n//go:generate stringer -type=Foo\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	has, err := fileContainsDirective(withDirective)
	if err != nil {
		t.Fatal(err)
	}
	if !has {
		t.Error("expected directive to be found")
	}

	has, err = fileContainsDirective(withoutDirective)
	if err != nil {
		t.Fatal(err)
	}
	if has {
		t.Error("expected directive not to be found")
	}
}

func assertContains(t *testing.T, got, want string) {
	t.Helper()
	if !strings.Contains(got, want) {
		t.Errorf("output does not contain %q\n\ngot:\n%s", want, got)
	}
}

func assertNotContains(t *testing.T, got, unwanted string) {
	t.Helper()
	if strings.Contains(got, unwanted) {
		t.Errorf("output should not contain %q\n\ngot:\n%s", unwanted, got)
	}
}
