// Code generated by dagnabit; DO NOT EDIT.

package env_vars

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/charlie/env_vars"

type BufferedCoderDotenv = internal.BufferedCoderDotenv
type DirectoryLayoutBaseEnvVar = internal.DirectoryLayoutBaseEnvVar
type DirectoryLayoutPath = internal.DirectoryLayoutPath

// TODO add support for comments
type EnvVars = internal.EnvVars
type Getenv = internal.Getenv

var GetOrPanic = internal.GetOrPanic
var Make = internal.Make
var MakeAbsolutePath = internal.MakeAbsolutePath
