// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package env_vars

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/charlie/env_vars"

type (
	BufferedCoderDotenv       = internal.BufferedCoderDotenv
	DirectoryLayoutBaseEnvVar = internal.DirectoryLayoutBaseEnvVar
	DirectoryLayoutPath       = internal.DirectoryLayoutPath
)

// TODO add support for comments
type (
	EnvVars = internal.EnvVars
	Getenv  = internal.Getenv
)

var (
	GetOrPanic       = internal.GetOrPanic
	Make             = internal.Make
	MakeAbsolutePath = internal.MakeAbsolutePath
)
