// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package nato_levels

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/0/nato_levels"

type NATOLevelMapper = internal.NATOLevelMapper

var MakeNATOLevelMapper = internal.MakeNATOLevelMapper
