// Code generated by dagnabit; DO NOT EDIT.

package nato_levels

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/nato_levels"

type NATOLevelMapper = internal.NATOLevelMapper

var MakeNATOLevelMapper = internal.MakeNATOLevelMapper
