// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package analyzer_repool

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/alfa/analyzer_repool"

var Analyzer = internal.Analyzer
