// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package analyzer_repool

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/alfa/analyzer_repool"

var Analyzer = internal.Analyzer
