// Code generated by dagnabit; DO NOT EDIT.

package cargo_workspace

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/cargo_workspace"

// Workspace is a located cargo workspace.
type Workspace = internal.Workspace

// FindRoot walks up from dir to the nearest Cargo.toml whose contents
// include a [workspace] table. Crate manifests without [workspace] are
// skipped (the walk continues upward). Errors when the filesystem root
// is reached without finding one.
var FindRoot = internal.FindRoot
