// Code generated by dagnabit; DO NOT EDIT.

package analyzer_paramobj

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/alfa/analyzer_paramobj"

var Analyzer = internal.Analyzer
