// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package analyzer_paramobj

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/alfa/analyzer_paramobj"

var Analyzer = internal.Analyzer
