// Code generated by dagnabit; DO NOT EDIT.

package topological_sort

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/topological_sort"

type (
	Edge = internal.Edge
)

var (
	Sort = internal.Sort
)
