// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package topological_sort

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/0/topological_sort"

// Edge is a directed dependency: Source depends on Target.
type Edge = internal.Edge

// Sort runs Kahn's algorithm on edges and returns a map from node name
// to its height in the dependency DAG. Returns an error if a cycle is
// detected.
var Sort = internal.Sort
