// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package xdg_defaults

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/delta/xdg_defaults"

type DefaultEnvVar = internal.DefaultEnvVar

var (
	Cache      = internal.Cache
	Config     = internal.Config
	Cwd        = internal.Cwd
	Data       = internal.Data
	Home       = internal.Home
	MakeGetenv = internal.MakeGetenv
	Runtime    = internal.Runtime
	State      = internal.State
)

const (
	VarUtilityName = internal.VarUtilityName
	VarXDGOverride = internal.VarXDGOverride
)
