// Code generated by dagnabit; DO NOT EDIT.

package xdg_defaults

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/delta/xdg_defaults"

type DefaultEnvVar = internal.DefaultEnvVar

var Cache = internal.Cache
var Config = internal.Config
var Cwd = internal.Cwd
var Data = internal.Data
var Home = internal.Home
var MakeGetenv = internal.MakeGetenv
var Runtime = internal.Runtime
var State = internal.State

const VarUtilityName = internal.VarUtilityName
const VarXDGOverride = internal.VarXDGOverride
