// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package debug

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/echo/debug"

type (
	Context = internal.Context
	Options = internal.Options
)

var MakeContext = internal.MakeContext
