// Code generated by dagnabit; DO NOT EDIT.

package debug

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/echo/debug"

type (
	Context = internal.Context
	Options = internal.Options
)

var (
	MakeContext = internal.MakeContext
)
