// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package vim_cli_options_builder

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/0/vim_cli_options_builder"

type Builder = internal.Builder

var New = internal.New
