// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package editor

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/echo/editor"

type (
	Editor = internal.Editor
	Type   = internal.Type
)

var (
	MakeEditor               = internal.MakeEditor
	MakeEditorWithVimOptions = internal.MakeEditorWithVimOptions
)

const (
	TypeUnknown = internal.TypeUnknown
	TypeVim     = internal.TypeVim
)
