// Code generated by dagnabit; DO NOT EDIT.

package editor

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/echo/editor"

type Editor = internal.Editor
type Type = internal.Type

var MakeEditor = internal.MakeEditor
var MakeEditorWithVimOptions = internal.MakeEditorWithVimOptions

const TypeUnknown = internal.TypeUnknown
const TypeVim = internal.TypeVim
