// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package tommy_util

import internal "code.linenisgreat.com/purse-first/libs/dewey/internal/delta/tommy_util"

var (
	BytesToMap    = internal.BytesToMap
	DocumentToMap = internal.DocumentToMap
	ReaderToMap   = internal.ReaderToMap
)
