// Code generated by dagnabit; DO NOT EDIT.

package tommy_util

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/delta/tommy_util"

var BytesToMap = internal.BytesToMap
var DocumentToMap = internal.DocumentToMap
var ReaderToMap = internal.ReaderToMap
