// Code generated by dagnabit (dev+unknown); DO NOT EDIT.

package tommy_util

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/delta/tommy_util"

var (
	BytesToMap    = internal.BytesToMap
	DocumentToMap = internal.DocumentToMap
	ReaderToMap   = internal.ReaderToMap
)
