// Code generated by dagnabit; DO NOT EDIT.

package cli

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/delta/cli"

// TODO add support for comma-separated values
type (
	CLICompleter           = internal.CLICompleter
	FlagSet                = internal.FlagSet
	FlagValueWithCompetion = internal.FlagValueWithCompetion
)

var FlagSetVarWithCompletion = internal.FlagSetVarWithCompletion
