// Code generated by dagnabit; DO NOT EDIT.

package catgut

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/delta/catgut"

type (
	MultiRuneReader               = internal.MultiRuneReader
	RingBuffer                    = internal.RingBuffer
	RingBufferRuneScanner         = internal.RingBufferRuneScanner
	RingBufferScanner             = internal.RingBufferScanner
	Scanner                       = internal.Scanner
	Slice                         = internal.Slice
	SliceBytes                    = internal.SliceBytes
	SliceReader                   = internal.SliceReader
	SliceRuneScanner              = internal.SliceRuneScanner
	SplitFunc                     = internal.SplitFunc
	SplitFuncExperimental         = internal.SplitFuncExperimental
	String                        = internal.String
	StringFormatReadWriter[T any] = internal.StringFormatReadWriter[T]
	StringFormatReader[T any]     = internal.StringFormatReader[T]
	StringFormatWriter[T any]     = internal.StringFormatWriter[T]
)

var (
	ErrBufferEmpty            = internal.ErrBufferEmpty
	ErrNoMatch                = internal.ErrNoMatch
	GetPool                   = internal.GetPool
	Make                      = internal.Make
	MakeErrLength             = internal.MakeErrLength
	MakeFromBytes             = internal.MakeFromBytes
	MakeFromReader            = internal.MakeFromReader
	MakeFromString            = internal.MakeFromString
	MakeMultiRuneReader       = internal.MakeMultiRuneReader
	MakeRingBuffer            = internal.MakeRingBuffer
	MakeRingBufferRuneScanner = internal.MakeRingBufferRuneScanner
	MakeRingBufferScanner     = internal.MakeRingBufferScanner
	MakeSliceReader           = internal.MakeSliceReader
	MakeSliceRuneScanner      = internal.MakeSliceRuneScanner
	MapTo                     = internal.MapTo
	NewScanner                = internal.NewScanner
	NewScannerExperimental    = internal.NewScannerExperimental
	StringFormatWriterString  = internal.StringFormatWriterString
	WriteKeySpaceValueNewline = internal.WriteKeySpaceValueNewline
	WriteLower                = internal.WriteLower
)

const (
	RingBufferDefaultSize = internal.RingBufferDefaultSize
)
