// Code generated by dagnabit; DO NOT EDIT.

package jsonrpc

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/jsonrpc"

type Conn = internal.Conn
type Error = internal.Error
type Handler = internal.Handler
type ID = internal.ID
type Message = internal.Message
type Stream = internal.Stream

var NewConn = internal.NewConn
var NewErrorResponse = internal.NewErrorResponse
var NewNotification = internal.NewNotification
var NewNumberID = internal.NewNumberID
var NewRequest = internal.NewRequest
var NewResponse = internal.NewResponse
var NewStream = internal.NewStream
var NewStringID = internal.NewStringID

const ContentModified = internal.ContentModified
const InternalError = internal.InternalError
const InvalidParams = internal.InvalidParams
const InvalidRequest = internal.InvalidRequest
const MethodNotFound = internal.MethodNotFound
const ParseError = internal.ParseError
const RequestCancelled = internal.RequestCancelled
const ServerNotInitialized = internal.ServerNotInitialized
const Version = internal.Version
