// Code generated by dagnabit; DO NOT EDIT.

package jsonrpc

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/golf/jsonrpc"

type (
	Conn    = internal.Conn
	Error   = internal.Error
	Handler = internal.Handler
	ID      = internal.ID
	Message = internal.Message
	Stream  = internal.Stream
)

var (
	NewConn          = internal.NewConn
	NewErrorResponse = internal.NewErrorResponse
	NewNotification  = internal.NewNotification
	NewNumberID      = internal.NewNumberID
	NewRequest       = internal.NewRequest
	NewResponse      = internal.NewResponse
	NewStream        = internal.NewStream
	NewStringID      = internal.NewStringID
)

const (
	ContentModified      = internal.ContentModified
	InternalError        = internal.InternalError
	InvalidParams        = internal.InvalidParams
	InvalidRequest       = internal.InvalidRequest
	MethodNotFound       = internal.MethodNotFound
	ParseError           = internal.ParseError
	RequestCancelled     = internal.RequestCancelled
	ServerNotInitialized = internal.ServerNotInitialized
	Version              = internal.Version
)
