// Code generated by tommy dev (unknown); DO NOT EDIT.

package script_config

import (
	"fmt"
	"strings"

	"code.linenisgreat.com/tommy/pkg/cst"
	"code.linenisgreat.com/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type WithOutputFormatDocument struct {
	data   WithOutputFormat
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeWithOutputFormat(input []byte) (*WithOutputFormatDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &WithOutputFormatDocument{
		cstDoc: doc,
		model:  model,
	}

	if _vDescription, _ok := model.Get("description"); _ok && _vDescription.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vDescription.Leaf); _xok {
			d.data.Description = _x
			_vDescription.MarkConsumed()
		}
	}
	if _vShell, _ok := model.Get("shell"); _ok && _vShell.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vShell.Leaf); _xok {
			d.data.Shell = _x
			if d.data.Shell == nil {
				d.data.Shell = []string{}
			}
			_vShell.MarkConsumed()
		}
	}
	if _vScript, _ok := model.Get("script"); _ok && _vScript.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vScript.Leaf); _xok {
			d.data.Script = _x
			_vScript.MarkConsumed()
		}
	}
	if _vEnv, _ok := model.Get("env"); _ok && _vEnv.Kind == cst.VTable {
		_vEnv.MarkSeen()
		d.data.Env = make(map[string]string)
		for _iEnv := range _vEnv.Fields {
			_fEnv := &_vEnv.Fields[_iEnv]
			if _fEnv.Val.Kind == cst.VLeaf {
				if _s, _sok := cst.ExtractString(_fEnv.Val.Leaf); _sok {
					d.data.Env[_fEnv.Key] = _s
					_fEnv.Val.MarkConsumed()
				}
			}
		}
	}
	if _vUti, _ok := model.Get("uti"); _ok && _vUti.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vUti.Leaf); _xok {
			d.data.UTI = _x
			_vUti.MarkConsumed()
		}
	}
	if _vUtis, _ok := model.Get("utis"); _ok && _vUtis.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vUtis.Leaf); _xok {
			d.data.UTIS = _x
			if d.data.UTIS == nil {
				d.data.UTIS = []string{}
			}
			_vUtis.MarkConsumed()
		}
	}
	if _vFileExtension, _ok := model.Get("file-extension"); _ok && _vFileExtension.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vFileExtension.Leaf); _xok {
			d.data.FileExtension = _x
			_vFileExtension.MarkConsumed()
		}
	}
	return d, nil
}

func (d *WithOutputFormatDocument) Data() *WithOutputFormat {
	return &d.data
}

func (d *WithOutputFormatDocument) Encode() ([]byte, error) {
	if d.data.Description != "" || cst.HasValue(d.cstDoc.Root(), "description") {
		if err := cst.SetAny(d.cstDoc.Root(), "description", d.data.Description); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		if len(d.data.Shell) > 0 || cst.HasValue(d.cstDoc.Root(), "shell") {
			if err := cst.SetAny(d.cstDoc.Root(), "shell", d.data.Shell); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.Script != "" {
		if err := cst.SetMultilineString(d.cstDoc.Root(), "script", d.data.Script); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "script")
	}
	if d.data.Env != nil {
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "env")
		cst.DeleteAllValues(tableNode)
		for k, v := range d.data.Env {
			if err := cst.SetAny(tableNode, k, v); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.UTI != "" || cst.HasValue(d.cstDoc.Root(), "uti") {
		if err := cst.SetAny(d.cstDoc.Root(), "uti", d.data.UTI); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		if d.data.UTIS != nil {
			if err := cst.SetAny(d.cstDoc.Root(), "utis", d.data.UTIS); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.FileExtension != "" || cst.HasValue(d.cstDoc.Root(), "file-extension") {
		if err := cst.SetAny(d.cstDoc.Root(), "file-extension", d.data.FileExtension); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *WithOutputFormatDocument) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *WithOutputFormatDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *WithOutputFormatDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *WithOutputFormatDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *WithOutputFormatDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeWithOutputFormatInto(data *WithOutputFormat, sub *cst.Value) error {
	if _vDescription, _ok := sub.Get("description"); _ok && _vDescription.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vDescription.Leaf); _xok {
			data.Description = _x
			_vDescription.MarkConsumed()
		}
	}
	if _vShell, _ok := sub.Get("shell"); _ok && _vShell.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vShell.Leaf); _xok {
			data.Shell = _x
			if data.Shell == nil {
				data.Shell = []string{}
			}
			_vShell.MarkConsumed()
		}
	}
	if _vScript, _ok := sub.Get("script"); _ok && _vScript.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vScript.Leaf); _xok {
			data.Script = _x
			_vScript.MarkConsumed()
		}
	}
	if _vEnv, _ok := sub.Get("env"); _ok && _vEnv.Kind == cst.VTable {
		_vEnv.MarkSeen()
		data.Env = make(map[string]string)
		for _iEnv := range _vEnv.Fields {
			_fEnv := &_vEnv.Fields[_iEnv]
			if _fEnv.Val.Kind == cst.VLeaf {
				if _s, _sok := cst.ExtractString(_fEnv.Val.Leaf); _sok {
					data.Env[_fEnv.Key] = _s
					_fEnv.Val.MarkConsumed()
				}
			}
		}
	}
	if _vUti, _ok := sub.Get("uti"); _ok && _vUti.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vUti.Leaf); _xok {
			data.UTI = _x
			_vUti.MarkConsumed()
		}
	}
	if _vUtis, _ok := sub.Get("utis"); _ok && _vUtis.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vUtis.Leaf); _xok {
			data.UTIS = _x
			if data.UTIS == nil {
				data.UTIS = []string{}
			}
			_vUtis.MarkConsumed()
		}
	}
	if _vFileExtension, _ok := sub.Get("file-extension"); _ok && _vFileExtension.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vFileExtension.Leaf); _xok {
			data.FileExtension = _x
			_vFileExtension.MarkConsumed()
		}
	}
	return nil
}

func EncodeWithOutputFormatFrom(data *WithOutputFormat, doc *document.Document, container *cst.Node) error {
	if data.Description != "" || cst.HasValue(container, "description") {
		if err := cst.SetAny(container, "description", data.Description); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		if len(data.Shell) > 0 || cst.HasValue(container, "shell") {
			if err := cst.SetAny(container, "shell", data.Shell); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.Script != "" {
		if err := cst.SetMultilineString(container, "script", data.Script); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "script")
	}
	if data.Env != nil {
		tableNode := cst.EnsureChildTable(doc.Root(), container, "env")
		cst.DeleteAllValues(tableNode)
		for k, v := range data.Env {
			if err := cst.SetAny(tableNode, k, v); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.UTI != "" || cst.HasValue(container, "uti") {
		if err := cst.SetAny(container, "uti", data.UTI); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		if data.UTIS != nil {
			if err := cst.SetAny(container, "utis", data.UTIS); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.FileExtension != "" || cst.HasValue(container, "file-extension") {
		if err := cst.SetAny(container, "file-extension", data.FileExtension); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
