// Code generated by tommy; DO NOT EDIT.

package script_config

import (
	"fmt"
	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
	"strings"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type WithOutputFormatDocument struct {
	data     WithOutputFormat
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeWithOutputFormat(input []byte) (*WithOutputFormatDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &WithOutputFormatDocument{
		consumed: make(map[string]bool),
		cstDoc:   doc,
	}

	for _, _kv := range d.cstDoc.Root().Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "description":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.Description = v
				d.consumed["description"] = true
			}
		case "shell":
			if v, ok := cst.ExtractStringSlice(_kv); ok {
				d.data.Shell = v
				d.consumed["shell"] = true
			}
		case "script":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.Script = v
				d.consumed["script"] = true
			}
		case "uti":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.UTI = v
				d.consumed["uti"] = true
			}
		case "utis":
			if v, ok := cst.ExtractStringSlice(_kv); ok {
				d.data.UTIS = v
				d.consumed["utis"] = true
			}
		case "file-extension":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.FileExtension = v
				d.consumed["file-extension"] = true
			}
		}
	}
	for _, _ch := range d.cstDoc.Root().Children {
		if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "env" {
			d.data.Env = cst.ExtractStringMap(_ch)
			d.consumed["env"] = true
			for _ik := range d.data.Env {
				d.consumed["env"+"."+_ik] = true
			}
			break
		}
	}
	return d, nil
}
func (d *WithOutputFormatDocument) Data() *WithOutputFormat {
	return &d.data
}
func (d *WithOutputFormatDocument) Encode() ([]byte, error) {
	if d.data.Description != "" || cst.HasValue(d.cstDoc.Root(), "description") {
		if err := cst.SetAny(d.cstDoc.Root(), "description", d.data.Description); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		if len(d.data.Shell) > 0 || cst.HasValue(d.cstDoc.Root(), "shell") {
			if err := cst.SetAny(d.cstDoc.Root(), "shell", d.data.Shell); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.Script != "" {
		if err := cst.SetMultilineString(d.cstDoc.Root(), "script", d.data.Script); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "script")
	}
	if len(d.data.Env) > 0 {
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "env")
		cst.DeleteAllValues(tableNode)
		for k, v := range d.data.Env {
			if err := cst.SetAny(tableNode, k, v); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.UTI != "" || cst.HasValue(d.cstDoc.Root(), "uti") {
		if err := cst.SetAny(d.cstDoc.Root(), "uti", d.data.UTI); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		if err := cst.SetAny(d.cstDoc.Root(), "utis", d.data.UTIS); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.FileExtension != "" || cst.HasValue(d.cstDoc.Root(), "file-extension") {
		if err := cst.SetAny(d.cstDoc.Root(), "file-extension", d.data.FileExtension); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}
func (d *WithOutputFormatDocument) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}
func (d *WithOutputFormatDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}
func (d *WithOutputFormatDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}
func (d *WithOutputFormatDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}
func (d *WithOutputFormatDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}
func DecodeWithOutputFormatInto(data *WithOutputFormat, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	for _, _kv := range container.Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "description":
			if v, ok := cst.ExtractString(_kv); ok {
				data.Description = v
				consumed[keyPrefix+"description"] = true
			}
		case "shell":
			if v, ok := cst.ExtractStringSlice(_kv); ok {
				data.Shell = v
				consumed[keyPrefix+"shell"] = true
			}
		case "script":
			if v, ok := cst.ExtractString(_kv); ok {
				data.Script = v
				consumed[keyPrefix+"script"] = true
			}
		case "uti":
			if v, ok := cst.ExtractString(_kv); ok {
				data.UTI = v
				consumed[keyPrefix+"uti"] = true
			}
		case "utis":
			if v, ok := cst.ExtractStringSlice(_kv); ok {
				data.UTIS = v
				consumed[keyPrefix+"utis"] = true
			}
		case "file-extension":
			if v, ok := cst.ExtractString(_kv); ok {
				data.FileExtension = v
				consumed[keyPrefix+"file-extension"] = true
			}
		}
	}
	for _, _ch := range doc.Root().Children {
		if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == keyPrefix+"env" {
			data.Env = cst.ExtractStringMap(_ch)
			consumed[keyPrefix+"env"] = true
			for _ik := range data.Env {
				consumed[keyPrefix+"env"+"."+_ik] = true
			}
			break
		}
	}
	return nil
}
func EncodeWithOutputFormatFrom(data *WithOutputFormat, doc *document.Document, container *cst.Node) error {
	if data.Description != "" || cst.HasValue(container, "description") {
		if err := cst.SetAny(container, "description", data.Description); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		if len(data.Shell) > 0 || cst.HasValue(container, "shell") {
			if err := cst.SetAny(container, "shell", data.Shell); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.Script != "" {
		if err := cst.SetMultilineString(container, "script", data.Script); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "script")
	}
	if len(data.Env) > 0 {
		tableNode := cst.EnsureChildTable(doc.Root(), container, "env")
		cst.DeleteAllValues(tableNode)
		for k, v := range data.Env {
			if err := cst.SetAny(tableNode, k, v); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.UTI != "" || cst.HasValue(container, "uti") {
		if err := cst.SetAny(container, "uti", data.UTI); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		if err := cst.SetAny(container, "utis", data.UTIS); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.FileExtension != "" || cst.HasValue(container, "file-extension") {
		if err := cst.SetAny(container, "file-extension", data.FileExtension); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
