// Code generated by dagnabit; DO NOT EDIT.

package pivy

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/delta/pivy"

type (
	ECDHFunc  = internal.ECDHFunc
	IOWrapper = internal.IOWrapper
	Identity  = internal.Identity
	Recipient = internal.Recipient
)

var (
	AgentECDHFunc          = internal.AgentECDHFunc
	CompressP256Point      = internal.CompressP256Point
	DecompressP256Point    = internal.DecompressP256Point
	ErrAgent               = internal.ErrAgent
	IsErrAgent             = internal.IsErrAgent
	NewAgentIdentity       = internal.NewAgentIdentity
	ResolveAgentSocketPath = internal.ResolveAgentSocketPath
	SoftwareECDHForTesting = internal.SoftwareECDHForTesting
)

const (
	StanzaTypePivyEcdhP256 = internal.StanzaTypePivyEcdhP256
)
