// Code generated by dagnabit; DO NOT EDIT.

package go_module

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/go_module"

var (
	ReadModulePath    = internal.ReadModulePath
	ResolveModulePath = internal.ResolveModulePath
)
