// Code generated by dagnabit; DO NOT EDIT.

package transport

import internal "github.com/amarbel-llc/purse-first/libs/dewey/internal/golf/transport"

type (
	Stdio     = internal.Stdio
	Transport = internal.Transport
)

var (
	NewStdio           = internal.NewStdio
	NewStdioWithCloser = internal.NewStdioWithCloser
)
