package dagnabit_rust

import (
	"bytes"
	"fmt"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"github.com/BurntSushi/toml"

	cargo_manifest "github.com/amarbel-llc/purse-first/libs/dewey/internal/0/cargo_manifest"
)

// generatedHeader is the first line of every generated lib.rs.
const generatedHeader = "// Code generated by dagnabit; DO NOT EDIT."

// Exporter generates <OutputDir>/ glob-facade crates (`pub use
// <internal>::*;`) from internal crates. Rust analog of dagnabit's
// Exporter: where the Go exporter enumerates symbols, Rust's glob
// re-export makes facades drift-proof by construction — the facade only
// names the internal crate, never its contents.
type Exporter struct {
	// WorkspaceRoot is the cargo workspace root directory (containing
	// the [workspace] Cargo.toml). Crate dirs given to ExportPackage
	// are slash-relative to it.
	WorkspaceRoot string

	// OutputDir is the facade output directory relative to
	// WorkspaceRoot. Defaults to "pkgs" when empty.
	OutputDir string

	// DryRun prints what would be generated without writing anything.
	DryRun bool

	// outputRoot, when non-empty, is the filesystem root facades are
	// written under in place of WorkspaceRoot. Check* methods redirect
	// it to a temp dir for a no-mutation drift comparison.
	outputRoot string

	// skipMembers disables the root-manifest members update. Set by
	// Check* methods, which must not mutate the real tree.
	skipMembers bool
}

// crateManifest is the subset of an internal crate's Cargo.toml the
// exporter reads (BurntSushi decode: full TOML semantics).
type crateManifest struct {
	Package struct {
		Name     string `toml:"name"`
		Version  string `toml:"version"`
		Edition  string `toml:"edition"`
		Metadata struct {
			Dagnabit struct {
				Export bool `toml:"export"`
			} `toml:"dagnabit"`
		} `toml:"metadata"`
	} `toml:"package"`
}

func (e *Exporter) outputDir() string {
	if e.OutputDir == "" {
		return "pkgs"
	}

	return e.OutputDir
}

// facadeRoot is the filesystem root facades are written under.
func (e *Exporter) facadeRoot() string {
	if e.outputRoot != "" {
		return e.outputRoot
	}

	return e.WorkspaceRoot
}

// ExportPackage generates the glob facade for the internal crate at
// crateDir (slash-relative to WorkspaceRoot): a facade Cargo.toml whose
// single dependency path-points at the internal crate, a one-line
// `pub use <internal>::*;` lib.rs, and an idempotent [workspace]
// members entry for the facade.
func (e *Exporter) ExportPackage(crateDir string) error {
	manifestPath := filepath.Join(
		e.WorkspaceRoot, filepath.FromSlash(crateDir), "Cargo.toml",
	)

	var manifest crateManifest
	if _, err := toml.DecodeFile(manifestPath, &manifest); err != nil {
		return fmt.Errorf("parsing %s: %w", manifestPath, err)
	}

	internalName := manifest.Package.Name
	facadeName := path.Base(crateDir)

	if internalName == facadeName {
		return fmt.Errorf(
			"internal crate %q must not use its facade name; rename it %q (convention: <name>_internal)",
			internalName,
			facadeName+"_internal",
		)
	}

	facadeRel := e.outputDir() + "/" + facadeName

	depRel, err := filepath.Rel(
		filepath.FromSlash(facadeRel), filepath.FromSlash(crateDir),
	)
	if err != nil {
		return fmt.Errorf(
			"computing path from %s to %s: %w", facadeRel, crateDir, err,
		)
	}

	facadeDir := filepath.Join(e.facadeRoot(), filepath.FromSlash(facadeRel))
	facadeManifestPath := filepath.Join(facadeDir, "Cargo.toml")
	libRSPath := filepath.Join(facadeDir, "src", "lib.rs")

	if e.DryRun {
		fmt.Printf("would generate: %s\n", facadeManifestPath)
		fmt.Printf("would generate: %s\n", libRSPath)
		fmt.Printf("would add workspace member: %s\n", facadeRel)

		return nil
	}

	// The facade's [package] keys are copied from the internal crate.
	// When the internal manifest omits edition (valid; cargo defaults
	// to 2015), the facade omits it too and inherits the same default —
	// emitting `edition = ""` would be rejected by cargo, and
	// defaulting to a newer edition would change semantics vs the
	// internal crate.
	editionLine := ""
	if manifest.Package.Edition != "" {
		editionLine = fmt.Sprintf("edition = %q\n", manifest.Package.Edition)
	}

	facadeManifest := fmt.Sprintf(
		"[package]\nname = %q\nversion = %q\n%s\n[dependencies]\n%s = { path = %q }\n",
		facadeName,
		manifest.Package.Version,
		editionLine,
		internalName,
		filepath.ToSlash(depRel),
	)

	libRS := generatedHeader + "\n\npub use " + internalName + "::*;\n"

	for _, file := range []struct {
		path    string
		content string
	}{
		{facadeManifestPath, facadeManifest},
		{libRSPath, libRS},
	} {
		if err := os.MkdirAll(filepath.Dir(file.path), 0o755); err != nil {
			return fmt.Errorf("creating output directory: %w", err)
		}

		if err := os.WriteFile(file.path, []byte(file.content), 0o644); err != nil {
			return fmt.Errorf("writing %s: %w", file.path, err)
		}

		fmt.Printf("generated: %s\n", file.path)
	}

	// Deliberately no formatter pass on the generated lib.rs: its
	// content is byte-canonical (rustfmt-clean) by construction, so
	// formatting would be a no-op when rustfmt is present — and when
	// rustfmt presence differs between the env that exported the
	// committed facades and the env running --check, a best-effort
	// formatter reintroduces env-dependent drift between export and
	// check. Same bug class as the Go exporter's checkExport temp-dir
	// formatting skew (#125).

	if e.skipMembers {
		return nil
	}

	return e.addMember(facadeRel)
}

// ExportAll exports every internal crate: each directory under
// internal/ (recursive) containing a Cargo.toml.
func (e *Exporter) ExportAll() error {
	crateDirs, err := e.internalCrateDirs()
	if err != nil {
		return err
	}

	for _, crateDir := range crateDirs {
		if err := e.ExportPackage(crateDir); err != nil {
			return fmt.Errorf("exporting %s: %w", crateDir, err)
		}
	}

	return nil
}

// ScanAndExport exports only the internal crates whose manifest opts in
// via `[package.metadata.dagnabit] export = true`.
func (e *Exporter) ScanAndExport() error {
	crateDirs, err := e.internalCrateDirs()
	if err != nil {
		return err
	}

	for _, crateDir := range crateDirs {
		manifestPath := filepath.Join(
			e.WorkspaceRoot, filepath.FromSlash(crateDir), "Cargo.toml",
		)

		var manifest crateManifest
		if _, err := toml.DecodeFile(manifestPath, &manifest); err != nil {
			return fmt.Errorf("parsing %s: %w", manifestPath, err)
		}

		if !manifest.Package.Metadata.Dagnabit.Export {
			continue
		}

		if err := e.ExportPackage(crateDir); err != nil {
			return fmt.Errorf("exporting %s: %w", crateDir, err)
		}
	}

	return nil
}

// CheckAll verifies every facade is in sync. See checkExport.
func (e *Exporter) CheckAll() error {
	// Full regeneration: an on-disk facade with no generated
	// counterpart is stale drift, so report those too.
	return e.checkExport(
		func(clone *Exporter) error { return clone.ExportAll() },
		true,
	)
}

// CheckPackage verifies a single crate's facade is in sync. See
// checkExport.
func (e *Exporter) CheckPackage(crateDir string) error {
	// Partial regeneration: only the named crate's files are in scope,
	// so do not flag unrelated on-disk facades as stale.
	return e.checkExport(
		func(clone *Exporter) error { return clone.ExportPackage(crateDir) },
		false,
	)
}

// CheckScan verifies the directive-marked crates' facades are in sync.
// See checkExport.
func (e *Exporter) CheckScan() error {
	return e.checkExport(
		func(clone *Exporter) error { return clone.ScanAndExport() },
		false,
	)
}

// checkExport regenerates facades into a temp dir (by running the given
// Export* method on a clone redirected there), then byte-compares the
// result against the committed WorkspaceRoot/<outputDir> tree — without
// writing to it or mutating the root manifest. It returns an error
// naming the drifted files (out of date, missing — not committed, or,
// when reportStale is set, stale — no longer generated), else nil.
func (e *Exporter) checkExport(run func(*Exporter) error, reportStale bool) error {
	tmp, err := os.MkdirTemp("", "dagnabit-rust-check-")
	if err != nil {
		return fmt.Errorf("creating temp dir: %w", err)
	}
	defer os.RemoveAll(tmp) //defer:err-checked temp-dir cleanup; failure must not clobber the real return

	clone := *e
	clone.outputRoot = tmp
	clone.skipMembers = true
	clone.DryRun = false

	if err := run(&clone); err != nil {
		return err
	}

	want := filepath.Join(e.WorkspaceRoot, e.outputDir())
	got := filepath.Join(tmp, e.outputDir())

	drift, err := diffFacadeTrees(want, got, e.outputDir(), reportStale)
	if err != nil {
		return err
	}

	if len(drift) > 0 {
		return fmt.Errorf(
			"%s/ is out of sync with internal/ (run `dagnabit export` and commit):\n  %s",
			e.outputDir(),
			strings.Join(drift, "\n  "),
		)
	}

	return nil
}

// diffFacadeTrees compares the committed facade tree (want) against a
// freshly generated one (got), returning a sorted list of
// human-readable drift entries prefixed with outputDir. Contents are
// compared at constructed paths — never resolved path strings — so
// symlinked temp dirs (macOS /var → /private/var) cannot produce
// phantom drift.
func diffFacadeTrees(want, got, outputDir string, reportStale bool) ([]string, error) {
	wantFiles, err := readTree(want)
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w", want, err)
	}

	gotFiles, err := readTree(got)
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w", got, err)
	}

	var drift []string

	for rel, gotBody := range gotFiles {
		wantBody, ok := wantFiles[rel]
		if !ok {
			drift = append(drift, outputDir+"/"+rel+" (missing — not committed)")

			continue
		}

		if !bytes.Equal(wantBody, gotBody) {
			drift = append(drift, outputDir+"/"+rel+" (out of date)")
		}
	}

	if reportStale {
		for rel := range wantFiles {
			if _, ok := gotFiles[rel]; !ok {
				drift = append(drift, outputDir+"/"+rel+" (stale — no longer generated)")
			}
		}
	}

	sort.Strings(drift)

	return drift, nil
}

// readTree maps each regular file under root to its contents, keyed by
// slash-relative path. A missing root yields an empty map.
func readTree(root string) (map[string][]byte, error) {
	files := map[string][]byte{}

	err := filepath.WalkDir(root, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			if os.IsNotExist(err) && p == root {
				return nil
			}

			return err
		}

		if d.IsDir() {
			return nil
		}

		data, err := os.ReadFile(p)
		if err != nil {
			return err
		}

		rel, err := filepath.Rel(root, p)
		if err != nil {
			return err
		}

		files[filepath.ToSlash(rel)] = data

		return nil
	})
	if err != nil {
		return nil, err
	}

	return files, nil
}

// internalCrateDirs walks WorkspaceRoot/internal and returns every
// directory containing a Cargo.toml, slash-relative to WorkspaceRoot,
// in deterministic (lexical) order.
func (e *Exporter) internalCrateDirs() ([]string, error) {
	internalDir := filepath.Join(e.WorkspaceRoot, "internal")

	var crateDirs []string

	err := filepath.WalkDir(internalDir, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if d.IsDir() || d.Name() != "Cargo.toml" {
			return nil
		}

		rel, err := filepath.Rel(e.WorkspaceRoot, filepath.Dir(p))
		if err != nil {
			return err
		}

		crateDirs = append(crateDirs, filepath.ToSlash(rel))

		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("walking %s: %w", internalDir, err)
	}

	return crateDirs, nil
}

// addMember appends rel to the root manifest's [workspace] members
// array (idempotent; the manifest is rewritten only when the entry was
// actually added).
func (e *Exporter) addMember(rel string) error {
	manifestPath := filepath.Join(e.WorkspaceRoot, "Cargo.toml")

	manifest, err := os.ReadFile(manifestPath)
	if err != nil {
		return fmt.Errorf("reading %s: %w", manifestPath, err)
	}

	out, added, err := cargo_manifest.AddMember(manifest, rel)
	if err != nil {
		return fmt.Errorf("adding workspace member %q in %s: %w", rel, manifestPath, err)
	}

	if !added {
		return nil
	}

	return writePreservingMode(manifestPath, out)
}
